### ISSUE TITLE
UDF功能发现bug：用户自定义函数类加载错误

### ISSUE THREAD

**Issue by YinChunGuang** [DTStack/flinkStreamSQL#104]
![flink5](https://user-images.githubusercontent.com/11421720/56486740-4f3db300-650b-11e9-848d-de9135f8fab9.png)
指定了udf的扩展函数路径，出现没有该方法。

**Comment by zoudaokoulife** [comment]
这个是一个bug；已经在修复了；

**Comment by lixiyuan123** [comment]
自定义函数的时候，我也遇到这个问题了，大佬大概时候会修复好？

**Comment by lixiyuan123** [comment]
> 这个是一个bug；已经在修复了；

大佬，我也遇到这个问题了，大概什么时候能修复好？

**Comment by yangsishu** [comment]
@zoudaokoulife 尽快修复下

**Comment by yangsishu** [comment]
已修复，master

**Comment by todd5167** [comment]
@YinChunGuang  1.5.1分支 修复

**Comment by tonybobam** [comment]
flink1.7.0分支好像没修复，有谁遇到一样的问题吗
