### ISSUE TITLE
寻求sqlParser相关的帮助

### ISSUE THREAD

**Issue by harbby** [DTStack/flinkStreamSQL#11]
Hi 袋鼠云:
    我是流计算项目 harbby/sylph 的作者。我在批流join, 以及sqlPaser方面碰到一些困难.
通过介绍发现你们解析做的非常棒，想多和你们进行一些交流和学习。

**Comment by yangsishu** [comment]
互相学习

**Comment by yangsishu** [comment]
能问下，你是哪个公司的吗

**Comment by harbby** [comment]
哈哈 纯属个人兴趣研究，不代表公司行为。

**Comment by harbby** [comment]
Hi 有更加方便的交流途径吗？

**Comment by yangsishu** [comment]
ysqwhiletrue 这是我的微信号

**Comment by caihuaxue** [comment]
我最近也在研究这个项目的源码，底层sql解析引擎，用的是apache calcite，这个有点复杂。
