### ISSUE TITLE
流异常是否会重复累加

### ISSUE THREAD

**Issue by latincross** [DTStack/flinkStreamSQL#113]
insert into
    result
select channel,
           info,
           pv+1 pv
    from a

假如stream insert一半的时候发生异常，流重启，pv是否会重复累加？

**Comment by yangsishu** [comment]
不会，flink会保证的

**Comment by latincross** [comment]
RetractJDBCOutputFormat    private void insertWrite(Row row) throws SQLException {

        updatePreparedStmt(row, upload);
        upload.addBatch();
        batchCount++;
        if (batchCount >= batchInterval) {
            upload.executeBatch();
            batchCount = 0;
        }
    }
