### ISSUE TITLE
流和维表join id字段类型不一致问题

### ISSUE THREAD

**Issue by chaiyuan2046** [DTStack/flinkStreamSQL#114]
1.6分支

流：kafka，join id 字段为varchar
维表：cassandra ，join id 字段为bigint
sql如：select * from kafka_table a left join cassandra_table b on a.id=b.id;
log如下图：
![image](https://user-images.githubusercontent.com/16013012/57372386-16b6fe00-71c8-11e9-97ce-401e4ba8caa6.png)

这种情况有什么好的办法处理么？

**Comment by chaiyuan2046** [comment]
用cast函数转换id类型会报错

**Comment by zoudaokoulife** [comment]
你这边用函数转换的具体的位置是哪里；sql贴出来看下；
我们这边方便跟下问题

**Comment by chaiyuan2046** [comment]
select * from kafka_table a left join cassandra_table b on cast(a.id as bigint)=b.id;
