### ISSUE TITLE
cassandra 维表join，cassandra session关闭问题

### ISSUE THREAD

**Issue by chaiyuan2046** [DTStack/flinkStreamSQL#115]
kafka只有部分数据能和cassandra 维表join上，后续报异常：
Failed to retrieve the data: Could not send request, session is closed
源码位置：
![image](https://user-images.githubusercontent.com/16013012/57447658-24cd5300-728a-11e9-8926-2dcbed82742c.png)

**Comment by chaiyuan2046** [comment]
fix
CassandraAsyncReqRow修改
![image](https://user-images.githubusercontent.com/16013012/57622507-57e05100-75c0-11e9-90cc-d1bfc1fed80e.png)

**Comment by a49a** [comment]
可以提个PR
