### ISSUE TITLE
1.6 yarnPer模式下 类加载报错

### ISSUE THREAD

**Issue by baochengjie** [DTStack/flinkStreamSQL#119]
![image](https://user-images.githubusercontent.com/33924130/57836489-6793ab80-77f3-11e9-93bc-6c1e218d234d.png)

**Comment by baochengjie** [comment]
所有nodeManager都copy,还出现错误

**Comment by ZSS2** [comment]
求问上述问题？如何解决的？为何为多Kafka11sink和Kafka11source文件夹？

**Comment by lixiyuan123** [comment]
我也遇到了这个问题，请问你现在解决了吗？
