### ISSUE TITLE
文档里有个错误

### ISSUE THREAD

**Issue by caihuaxue** [DTStack/flinkStreamSQL#12]
1.4.2 命令行参数选项

model

描述：执行模式，也就是flink集群的工作模式
local: 本地模式
standalone: 独立部署模式的flink集群
yarn: yarn模式的flink集群
必选：否
默认值：local

这里的“model”应该改为“mode“，表示运行模式。

**Comment by nuaabuaa07** [comment]
linux中命令行提交参数如下：
sh ./submit.sh -sql /home/javajzl/testFile/flink/sqlTXT/sideSql.txt  -name xctest -remoteSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins   -localSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins   -mode local   -confProp {\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000}
为啥报confProp参数错误。这里是反斜杠引起的吗？
![image](https://user-images.githubusercontent.com/25834421/47154654-7e355b00-d315-11e8-95c9-c983a7460b9b.png)

**Comment by yangsishu** [comment]
要加 \转义
-confProp {\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000}

**Comment by yangsishu** [comment]
是的命令行提交把 反斜杆 去掉
