### ISSUE TITLE
二次开发应该基于哪个分支？

### ISSUE THREAD

**Issue by lycbug666** [DTStack/flinkStreamSQL#121]
首先感谢袋鼠云的小伙伴们开源了这个项目！ 
现在我想基于这个项目进行二次开发，但是不知道应该基于哪个分支进行开发。
目前我发现 master 分支的 flink 版本为 1.5.4，v1.6.0_release 分支的代码基于 1.6.2，请问哪个才是稳定版本？

**Comment by yangsishu** [comment]
master 这个是代码最全也是最稳定的

**Comment by yangsishu** [comment]
后面会把代码合并到1.6x分支

**Comment by lycbug666** [comment]
> 后面会把代码合并到1.6x分支

好的，了解，那我还是基于master开发。
