### ISSUE TITLE
请问一下同时支持维表和table function吗

### ISSUE THREAD

**Issue by jsnorman** [DTStack/flinkStreamSQL#124]
insert into stat_orders_dclog
SELECT 
    b.name, 
    a.age 
FROM (select  newuserid, age from orders LEFT JOIN LATERAL TABLE(demoFunc(userid)) as T(newuserid) ON TRUE) a join side_order b on a.newuserid = b.userid;

类似与这样的语法，parse会将tablefuntion的语法( LEFT JOIN LATERAL TABLE)解析为一个新的left join，但是其实这不是一个left join

**Comment by yangsishu** [comment]
@zoudaokoulife 这个验证下是不是有问题

**Comment by zoudaokoulife** [comment]
我们本地验证下
