### ISSUE TITLE
输出到外部mysql表replace的支持问题

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#13]
项目目前支持输出到外部mysql表，使用replace操作吗？比如主键冲突时直接覆盖更新。我测试试，貌似只支持insert into 操作。

**Comment by nuaabuaa07** [comment]
我使用的是core模块里面的测试案例SideSqlExecTest.class提交测试的。测试中发现。
1.当mysql中设置了主键，使用“insert into”操作，会覆盖更新mysql表里相应主键的条目。
2.无论mysql中设置主键还是取消主键，使用“replace into”操作都会报错。
sql语句如下：
 replace
 into
	MyResult
	select 
		count(1) as id,
		MyTable.name
	from
		MyTable
	group by
		MyTable.name;

错误提示如下：
![image](https://user-images.githubusercontent.com/25834421/47193122-dc008c00-d383-11e8-91b3-3ea70549c757.png)

**Comment by yangsishu** [comment]
语法你只能写insert into，但是底层mysql的操作是replace into 操作

**Comment by nuaabuaa07** [comment]
明白了。

**Comment by harbby** [comment]
最好能允许 用户自己填写语句;
如:  ```replace into table select '${0}', ifnull((select cnt from table where id = '${0}'),0)+{1}```
例如: https://harbby.github.io/project/sylph/zh-cn/docs/intro/quickstart.html#demo1

**Comment by yangsishu** [comment]
可以考虑

**Comment by zhangzaixuan** [comment]
结果表 的声明需要加些特定配置吗
