### ISSUE TITLE
LRU 缓存是否支持分布式存储

### ISSUE THREAD

**Issue by yelijun** [DTStack/flinkStreamSQL#130]
缓存是否支持分布式存储？

如果只能单机，极端情况下是否可能会出现集群每台机器拥有相同的缓存？

**Comment by yangsishu** [comment]
不支持分布式存储，会做keyby的，每台机器的的维表缓存不一样的

**Comment by yelijun** [comment]
那是不是计算的时候 需要把数据 根据key 指定到机器？
不然 缓存不在这台机器上 要怎么处理？

**Comment by yangsishu** [comment]
keyby这个框架会自动处理的

**Comment by yangsishu** [comment]
缓存没有，会直接到第三方存储获取的

**Comment by yelijun** [comment]
okay，我去了解下 这个keyby
你们后面还是会继续用这个包的嘛？

> org.apache.flink.calcite.shaded.com.google.common.cache.Cache;
org.apache.flink.calcite.shaded.com.google.common.cache.CacheBuilder;

**Comment by yangsishu** [comment]
我们的框架

**Comment by yelijun** [comment]
okay，谢谢杨老师
