### ISSUE TITLE
join  超过三个条件的时候报错

### ISSUE THREAD

**Issue by YinChunGuang** [DTStack/flinkStreamSQL#132]
join  超过三个条件的时候报错，select a.name,a.age from a join a on a.id=b.id and a.name=b.name and a.age =b.age

**Comment by YinChunGuang** [comment]
测试达到三个的时候报错，
com.dtstack.flink.sql.side.SideSqlExec.getConditionFields( ) 没有做第二层处理 andNode转equals

**Comment by zoudaokoulife** [comment]
我们内部修复下，之后会推上来

**Comment by todd5167** [comment]
master分支解决 @YinChunGuang
