### ISSUE TITLE
linux命令提交任务，参数解析失败

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#14]
以下为linux命令行提交任务（在命令行提交时，去掉了参数中的反斜杠转义）：
sh ./submit.sh -sql /home/javajzl/testFile/flink/sqlTXT/sideSql.txt  -name xctest -remoteSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins   -localSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins   -mode local   -confProp {"time.characteristic":"EventTime","sql.checkpoint.interval":10000}

nohup日志中显示-confProp的参数解析错误（以上命令在测试类中提交任务，可以成功）：
![image](https://user-images.githubusercontent.com/25834421/47193582-4adee480-d386-11e8-928a-a157c2545b97.png)

**Comment by yangsishu** [comment]
是的，文档已经更新了

**Comment by nuaabuaa07** [comment]
通过linux命令行提交任务需要加反斜杠的，需要在大花括号和引号前面都用反斜杠的。
sh ./submit.sh -sql /home/javajzl/testFile/flink/sqlTXT/sideSql.txt -name xctest -remoteSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins -localSqlPluginPath /home/javajzl/testFile/flink/flinkStreamSQL-master/plugins -mode local -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}
