### ISSUE TITLE
运行在Hadoop3报错如下

### ISSUE THREAD

**Issue by lixiyuan123** [DTStack/flinkStreamSQL#143]
运行在hadoop3的时候报错如下，请问大神有解决的办法吗？

source是：kafka
sink是：console

org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: org.apache.flink.table.plan.nodes.datastream.StreamScan$$anon$1
ClassLoader info: URL ClassLoader:
    file: '/opt/soft/myflink/flinkstreamsql/plugins/kafka11source/kafka11-source.jar' (valid JAR)
    file: '/opt/soft/myflink/flinkstreamsql/plugins/consolesink/console-sink.jar' (valid JAR)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:267)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)

**Comment by yangsishu** [comment]
还没测试过hadoop3

**Comment by yangsishu** [comment]
插进包是需要在每台机器上都有的

**Comment by lixiyuan123** [comment]
> 插进包是需要在每台机器上都有的

已经确定每个机器上都有了，因为用hadoop2运行的没问题，切换到hadoop3就发现了这个问题。 大神能推测出来大概是什么原因吗？

**Comment by lixiyuan123** [comment]
> 还没测试过hadoop3

大神有空的时候帮忙测一下，现在基于咱们开源的这个项目在hadoop2上上了一个项目，现在集群要升级，升级到hadoop3，发现升级到hadoop3以后 flinkstreamsql跑不通了，把能试过的方式都试过了依然不行。感谢。

**Comment by lixiyuan123** [comment]
这个问题已经解决了，原因是我的jar包路径有问题。flinkstreamsql 项目是可以正常运行在Hadoop3上的。

**Comment by qiuqingyu** [comment]
> 这个问题已经解决了，原因是我的jar包路径有问题。flinkstreamsql 项目是可以正常运行在Hadoop3上的。

您好，我现在也遇到了这个问题，检查了plugins的路径没有问题啊，可是也报这个错误
