### ISSUE TITLE
join+window的异常

### ISSUE THREAD

**Issue by jonsnow233** [DTStack/flinkStreamSQL#145]
hi，我的source table是CREATE TABLE MyTable (
	udid VARCHAR,
	click INT,
	time BIGINT,
	WATERMARK FOR time AS withOffset (time, 10)
) WITH (
	type = 'kafka',
	bootstrapServers = 'xxxx:9092,xxx:9092',
	offsetReset = 'latest',
	topic = 'flinkwindow_test',
	parallelism = '1'
); 
side表，sink表省略。。。
然后我写了
INSERT INTO MyResult SELECT
	a.udid,
	TUMBLE_END (
		a.rowtime,
		INTERVAL '10' SECOND
	),
	sum(cast(b.click AS INT))
FROM
	MyTable a
JOIN sideTable b ON a.udid = b.udidmd5
GROUP BY
	TUMBLE (
		a.rowtime,
		INTERVAL '10' SECOND
	),
	a.udid
然后发现两个问题，一个是窗口只计算一次，后面就不计算了，还有一个是计算出来的窗口结束时间变成了protime。
但是如果把sql的join删掉，变成如下
INSERT INTO MyResult SELECT
	a.udid,
	TUMBLE_END (
		a.rowtime,
		INTERVAL '10' SECOND
	),
	sum(cast(b.click AS INT))
FROM
	MyTable a
GROUP BY
	TUMBLE (
		a.rowtime,
		INTERVAL '10' SECOND
	),
	a.udid
就没有上述两个问题了，我不知道是用法还是bug

**Comment by yangsishu** [comment]
能把完整的sql贴出来吗

**Comment by yangsishu** [comment]
还有用的是那个分支

**Comment by jonsnow233** [comment]
sql就是这个，
INSERT INTO MyResult SELECT
a.udid,
TUMBLE_END (
a.rowtime,
INTERVAL '10' SECOND
),
sum(cast(b.click AS INT))
FROM
MyTable a
JOIN sideTable b ON a.udid = b.udidmd5
GROUP BY
TUMBLE (
a.rowtime,
INTERVAL '10' SECOND
),
a.udid
用的是master分支

**Comment by a49a** [comment]
使用1.8_release 或者 1.10_release分支
