### ISSUE TITLE
mvn编译问题

### ISSUE THREAD

**Issue by aigod** [DTStack/flinkStreamSQL#147]
最新的master分支，按照首页的mvn编译， 报错，非法的转义符
[ERROR] C:\Users\Administrator\Desktop\files\flink\flinkStreamSQL-master\kafka09\kafka09-source\src\main\java\com\dtstack\flink\sql\source\kafka\table\KafkaSourceParser.java:[44,78] 错误: 非法转义符

**Comment by jonsnow233** [comment]
复制到nodepad++，再复制回来就好了

**Comment by yangsishu** [comment]
已修改
