### ISSUE TITLE
请问哪个分支支持kafka读取嵌套json

### ISSUE THREAD

**Issue by jonsnow233** [DTStack/flinkStreamSQL#155]

**Comment by yangsishu** [comment]
master分支

**Comment by AccordwangAccord** [comment]
@jonsnow233 请问下 
这种的嵌套怎么不支持啊？试过了获取不到啊a[0].name:
{"a":
[
 {"name":"eee","addr":"jiangsu",
    "b":
         [
		 {"code":"123","shop_id":"123"},
		 {"code":"234","shop_id":"245"}
		 ]
 }
]
,"gmt_create":"2019-10-09","store_id":"567"
}

**Comment by jonsnow233** [comment]
检查一下格式，如果还是不行的话可以自己开发




------------------ 原始邮件 ------------------
发件人: "AccordwangAccord"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午5:44
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com>;
抄送: "陈勇"<me1193216154@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DTStack/flinkStreamSQL] 请问哪个分支支持kafka读取嵌套json (#155)




@jonsnow233 请问下
 这种的嵌套怎么不支持啊？试过了获取不到啊a[0].name:
 {"a":
 [
 {"name":"eee","addr":"jiangsu",
 "b":
 [
 {"code":"123","shop_id":"123"},
 {"code":"234","shop_id":"245"}
 ]
 }
 ]
 ,"gmt_create":"2019-10-09","store_id":"567"
 }
