### ISSUE TITLE
timezone异常

### ISSUE THREAD

**Issue by tonybobam** [DTStack/flinkStreamSQL#156]
v1.7.0_dev分支，当kafka作为源表，timezone=Asia/Shanghai，使用window+join操作后，窗口时间比实际时间早了整八小时，水位线时间延后8小时，导致后续数据被认为超时丢弃，窗口只触发一次，有什么解决办法吗

**Comment by tonybobam** [comment]
当不使用join操作，水位线和窗口时间，事件时间是正常的

**Comment by tonybobam** [comment]
flink本身时区问题

**Comment by hqisog** [comment]
这个时区问题解决了吗
