### ISSUE TITLE
sink到kafka11，没有demo介绍啊？麻烦告知一下

### ISSUE THREAD

**Issue by AccordwangAccord** [DTStack/flinkStreamSQL#162]

**Comment by xuxiaoxiao89** [comment]
--该用例实现了Flink SQL实时读取kafka消息，经过业务逻辑sql后将结果输出到Kafka数据源中

--Kafka数据源
--kafka中的样例数据，必须为json格式：
/*
{"user_id":1,"age":10}
{"user_id":2,"age":30}
{"user_id":3,"age":11}
{"user_id":4,"age":22}
{"user_id":5,"age":13}
{"user_id":6,"age":8}
{"user_id":7,"age":15}
{"user_id":8,"age":66}
*/


CREATE TABLE MyTable(
    user_id int,
    age int
 )WITH(
    type ='kafka10',--必填
    bootstrapServers ='10.21.35.124:21005,10.21.35.125:21005,10.21.35.126:21005',--必填
    zookeeperQuorum ='10.21.35.120:24002,10.21.35.121:24002,10.21.35.122:24002/kafka',--必填
    offsetReset ='latest',
    groupId='test',
    topic ='test02',--必填，若多个可以用,隔开
    parallelism ='3'
 );

CREATE TABLE MyResult(
    id int,
	age int
 )WITH(
    type ='kafka10',--必填
	bootstrapServers ='10.21.35.124:21005,10.21.35.125:21005,10.21.35.126:21005',--必填
	topic='test03',--必填
	kafka.buffer.memory=33554432
 );
 
insert
into
    MyResult
	--以下为业务逻辑SQL
    select
		user_id,
		age
    from
        MyTable
    where
        age > 10

**Comment by xuxiaoxiao89** [comment]
这个是10的版本，也可以用到0.11的kafka，我的集群就是0.11的版本的，都是可以的

**Comment by AccordwangAccord** [comment]
@xuxiaoxiao89 谢谢

**Comment by qiuqingyu** [comment]
> 这个是10的版本，也可以用到0.11的kafka，我的集群就是0.11的版本的，都是可以的

@xuxiaoxiao89 麻烦问一下，我是按照您写的sql，但是执行的时候报错 #189

**Comment by AccordwangAccord** [comment]
@xuxiaoxiao89 请问下
这种的嵌套怎么不支持啊？试过了获取不到啊a[0].name和b[0].code:
{"a":
[
 {"name":"eee","addr":"jiangsu",
    "b":
         [
		 {"code":"123","shop_id":"123"},
		 {"code":"234","shop_id":"245"}
		 ]
 }
]
,"gmt_create":"2019-10-09","store_id":"567"
}
