### ISSUE TITLE
准备何时支持下 topn算子呢

### ISSUE THREAD

**Issue by hupper0** [DTStack/flinkStreamSQL#172]
准备何时支持下 topn算子呢~

**Comment by yangsishu** [comment]
flink1.9 用blink引擎已经有topn了

**Comment by hupper0** [comment]
但是感觉语法 和 标准的sql不太一样。。

**Comment by deadwind4** [comment]
参考原生Flink SQL TopN使用方法。

**Comment by a49a** [comment]
参考原生Flink SQL TopN使用方法。

https://ci.apache.org/projects/flink/flink-docs-master/dev/table/sql/queries.html#top-n

**Comment by deadwind4** [comment]
参考原生 Flink SQL TopN 使用方法。
