### ISSUE TITLE
stand alone udf 加载报错

### ISSUE THREAD

**Issue by zhougit86** [DTStack/flinkStreamSQL#174]
@yangsishu 

您好，我在使用standalone cluster的udf功能，当指定addjar后，在路径下放入

package cn.zxg.udf;

import org.apache.flink.table.functions.ScalarFunction;

/**
 *
 * @author zhouxiaogang
 * @version $Id: MyScalaFunction.java, v 0.1 2019-08-22 16:44
zhouxiaogang Exp $$
 */
public class MyScalaFunction extends ScalarFunction {

    public long eval(Long s) {
        return s*5 ;
    }

}

的origin jar包，系统报错 scalarFunction无法加载

java.lang.NoClassDefFoundError: org/apache/flink/table/functions/ScalarFunction

**Comment by yangsishu** [comment]
用的是那个版本

**Comment by a49a** [comment]
集群 flink/lib 保证 table-common.jar包存在
