### ISSUE TITLE
@taiziwang   1.8推了

### ISSUE THREAD

**Issue by taiziwang** [DTStack/flinkStreamSQL#180]
@taiziwang   1.8推了

_Originally posted by @todd5167 in https://github.com/DTStack/flinkStreamSQL/issues/177#issuecomment-526806390_

调用MyLocalStreamEnvironment报如下错误：
  cloud not create the dispatcherResourceManagerComponent 
caused by :java.net.BindException: cloud not start rest endpoint on any port in port range 8081
 有遇到这个本地运行问题没？

**Comment by wenbaoup** [comment]
这个问题是端口被占用了 在MyLocalStreamEnvironment类的execute()方法加 configuration.setString(RestOptions.ADDRESS, "9091");  端口地址随便给能用就行  我这边用的是1.9的 希望能解决你的问题
