### ISSUE TITLE
1.9合并

### ISSUE THREAD

**Issue by wenbaoup** [DTStack/flinkStreamSQL#181]
我这边升级到了1.9 本地测试通过和yarn任务提交了 但是还没有上生产环境测验过而且现在只有kafka source和kudu(side和sink)    flinkStreamSQL这边对1.9的计划是什么  大概几时会拉新的分支

**Comment by yangsishu** [comment]
1.9暂时没有计划，我们现在在测试1.8

**Comment by yangsishu** [comment]
1.9其实是一个beta版本，blink还没有完全的融合到flink里；所以我们还不会急着去兼容1.9

**Comment by wenbaoup** [comment]
好的 了解

**Comment by qiuqingyu** [comment]
麻烦问下，您这边是实现了flink 1.9版本的么？升级版本的成本高不高？

**Comment by wenbaoup** [comment]
@qiuqingyu 我这边1.9还是测试阶段，不过升级1.9感觉并不太好，成本一般还是比较兼容的。我这边目前还是以1.8为主。

**Comment by qiuqingyu** [comment]
> @qiuqingyu 我这边1.9还是测试阶段，不过升级1.9感觉并不太好，成本一般还是比较兼容的。我这边目前还是以1.8为主。

哦哦，这样啊，因为我们线上Flink是1.9的版本，所以想问下flinkStreamSQL如果能够兼容1.9的话就最好了，如果不可以就是得自己适配一下

**Comment by qiuqingyu** [comment]
> @qiuqingyu 我这边1.9还是测试阶段，不过升级1.9感觉并不太好，成本一般还是比较兼容的。我这边目前还是以1.8为主。

另外想问下，这个感觉并不太好是哪里？

**Comment by wenbaoup** [comment]
> > @qiuqingyu 我这边1.9还是测试阶段，不过升级1.9感觉并不太好，成本一般还是比较兼容的。我这边目前还是以1.8为主。
> 
> 另外想问下，这个感觉并不太好是哪里？
   flinkStreamSQL目前没有1.9分支 这个需要自己适配一下。然后不太好的方面主要是 1.9API兼容性的问题

**Comment by a49a** [comment]
已经支持1.10版本
