### ISSUE TITLE
提交后没有错误日志，flink web界面没有在运行的任务

### ISSUE THREAD

**Issue by jianghanfen** [DTStack/flinkStreamSQL#185]
flinkStreamSQL-1.6.0_release和flink-1.6.2 local一起使用（都在同一台机器），提交后没有错误日志，flink web界面没有在运行的任务。

提交命令如下：
sh submit.sh -sql /home/jianghanfen/flinkStreamSQL-1.6.0_release/flinkStreamSQL-1.6.0_release/dengta_sql/flinkStreamSQL_test.sql -name dengta_test -localSqlPluginPath ../plugins -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}

日志如下：
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Connected to JobManager at Actor[akka://flink/user/jobmanager_1#2003321585] with leader session id aa93e3f2-bb3c-4618-9dfb-80dc6a428b7f.
09/12/2019 09:53:04     Job execution switched to status RUNNING.
09/12/2019 09:53:04     Source: test_test_source -> Map -> to: Row -> Timestamps/Watermarks -> from: (word, report_time, ROWTIME) -> select: (word, 1 AS $f1, report_time)(1/1) switched to SCHEDULED 
09/12/2019 09:53:04     groupBy: (word), select: (word, COUNT(*) AS $f1, MIN(report_time) AS min_report_time, MAX(report_time) AS max_report_time) -> to: Tuple2 -> Sink: Unnamed(1/1) switched to SCHEDULED 
09/12/2019 09:53:04     Source: test_test_source -> Map -> to: Row -> Timestamps/Watermarks -> from: (word, report_time, ROWTIME) -> select: (word, 1 AS $f1, report_time)(1/1) switched to DEPLOYING 
09/12/2019 09:53:04     groupBy: (word), select: (word, COUNT(*) AS $f1, MIN(report_time) AS min_report_time, MAX(report_time) AS max_report_time) -> to: Tuple2 -> Sink: Unnamed(1/1) switched to DEPLOYING 
09/12/2019 09:53:04     groupBy: (word), select: (word, COUNT(*) AS $f1, MIN(report_time) AS min_report_time, MAX(report_time) AS max_report_time) -> to: Tuple2 -> Sink: Unnamed(1/1) switched to RUNNING 
09/12/2019 09:53:04     Source: test_test_source -> Map -> to: Row -> Timestamps/Watermarks -> from: (word, report_time, ROWTIME) -> select: (word, 1 AS $f1, report_time)(1/1) switched to RUNNING

**Comment by lu-uux** [comment]
local模式不会在web界面有显示的，至少是standalone模式吧

**Comment by jianghanfen** [comment]
local模式，也没见往redis sink结果？

**Comment by jianghanfen** [comment]
> local模式不会在web界面有显示的，至少是standalone模式吧

local模式任务不会跑吗？ 也没见往redis sink结果

**Comment by lu-uux** [comment]
看你的运行日志是没有问题的，确认是不是sql脚本的问题

**Comment by jianghanfen** [comment]
> 看你的运行日志是没有问题的，确认是不是sql脚本的问题

怎么判断sql脚本是否有问题呢？有相关日志可以查看没？  
sql脚本 如下：

CREATE TABLE test_source(
    word VARCHAR,
    report_time TIMESTAMP,
    WATERMARK FOR report_time AS withOffset( report_time , 1000 )
 )WITH(
    type ='kafka09',
    kafka.bootstrap.servers ='bigdata001:9092,bigdata002:9092,bigdata003:9092,bigdata004:9092,bigdata005:9092',
    kafka.zookeeper.quorum ='bigdata003:2181,bigdata004:2181,bigdata005:2181',
    kafka.auto.offset.reset ='latest',
    kafka.topic ='test',
    kafka.group.id = 'jhf',
    parallelism ='1',
    timezone='Asia/Shanghai',
    sourcedatatype ='json' #可不设置
 );
 
 CREATE TABLE test_sink(
    word VARCHAR,
    c BIGINT,
        min_report_time TIMESTAMP,
        max_report_time TIMESTAMP,
        PRIMARY KEY(word)
 )WITH(
    type ='redis',
    url = '192.168.9.81:6379',
    tableName ='test_sink',
    parallelism ='1',
        redisType = '1'
 );
 
 insert into test_sink select word,cast(count(1) as BIGINT) as c,min(report_time) as min_report_time,max(report_time) as max_report_time from test_source group by word;

**Comment by jianghanfen** [comment]
> 看你的运行日志是没有问题的，确认是不是sql脚本的问题

用flinkStreamSQL-1.5.2_release和flink1.5.4local模式，也有相同的问题，请问怎么解决？

**Comment by todd5167** [comment]
@jianghanfen  local模式可以直接在IDEA里面调试下，看看数据有没有正确解析出来，sql可以先写简单点，保证数据先插入进去。
