### ISSUE TITLE
关于连续join的问题

### ISSUE THREAD

**Issue by jonsnow233** [DTStack/flinkStreamSQL#187]
请问这种语法有没有打算支持
select 
   a.suid,
   a.click,
   b.name,
   c.name
from
  MyTable a
  JOIN sideTable b
  on a.suid=b.suid
  JOIN sideTable c
  on a.suid=c.suid

**Comment by yangsishu** [comment]
现在连续join只能是括号，暂时没打算

**Comment by yangsishu** [comment]
后面会支持这个语法

**Comment by yangsishu** [comment]
这个已经支持了
