### ISSUE TITLE
standalone模式找不到集群

### ISSUE THREAD

**Issue by jianghanfen** [DTStack/flinkStreamSQL#188]
这个问题怎么解决啊？standalone模式找不到集群，我也遇到同样的问题
https://github.com/DTStack/flinkStreamSQL/issues/92#issue-419788351

**Comment by guanxianchun** [comment]
我也遇到同样的问题

**Comment by guanxianchun** [comment]
![image](https://user-images.githubusercontent.com/12387037/70629230-9e844f80-1c64-11ea-87f5-88aae246a75e.png)

**Comment by a49a** [comment]
试下1.10_release分支
