### ISSUE TITLE
可以sink表(redis)中的一条数据用1个key吗？

### ISSUE THREAD

**Issue by jianghanfen** [DTStack/flinkStreamSQL#191]
redis sink 写入redis后，发现key是 表名:主键名:主键值:列名 ，也就是sink表（redis）如果有10列的话，sink表的1条数据在redis中要用10个key去存。可以sink表中的一条数据用1个key吗？
（用的是flinkStreamSQL-1.5.2_release standalone模式）

**Comment by xiuzhu9527** [comment]
目前还不可以

**Comment by hengyuan** [comment]
你可以改写一下RedisOutputFormat类，按照你需要的格式进行存储

**Comment by hengyuan** [comment]
我们现在是主键是：表名'\001'主键值    然后后边是把所有字段用'\001'分隔的字符串直接存储的
