### ISSUE TITLE
yarnPer 模式  插件无法加载什么问题

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkStreamSQL#193]
Cannot load user class: com.dtstack.flink.sql.source.kafka.CustomerKafka09Consumer

**Comment by qiuqingyu** [comment]
我也遇到了这个问题，麻烦问下解决了么

**Comment by maidou75293** [comment]
我看了源码，源码 没有加载 插件 jar

**Comment by qiuqingyu** [comment]
> 我看了源码，源码 没有加载 插件 jar

哈？我看着是有的啊？那你修改了哪里？方便说一下么？谢谢

**Comment by todd5167** [comment]
@maidou75293 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

**Comment by qiuqingyu** [comment]
> @maidou75293 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

@todd5167 不好意思，我今天试了下，报错还是和之前一样，提示plugin找不到，报错信息和之前一样

**Comment by todd5167** [comment]
@qiuqingyu 是不是插件地址没配置对？发下你完整的提交配置吧

**Comment by qiuqingyu** [comment]
> @qiuqingyu 是不是插件地址没配置对？发下你完整的提交配置吧

@todd5167 这是我提交的完整配置，麻烦看下，我把plugin插件拷贝到了各个节点的相同目录下
sh bin/submit.sh -sql /home/v11103357/flinkStreamSQL/test.sql -name test -localSqlPluginPath /home/v11103357/flinkStreamSQL/plugins -mode yarn -remoteSqlPluginPath /home/v11103357/flinkStreamSQL/plugins -flinkconf /home/v11103357/flink-1.8.2/conf -yarnconf /etc/hadoop/conf -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\} -flinkJarPath /home/v11103357/flink-1.8.2/lib

**Comment by lu-uux** [comment]
遇到同样的问题，找不到插件中的jar，把插件中需要的jar copy到classpath下可以启动

**Comment by qiuqingyu** [comment]
> 遇到同样的问题，找不到插件中的jar，把插件中需要的jar copy到classpath下可以启动

在服务器上没有向path下写入的权限，就是在path下把plugin的路径加进去就可以么？这是因为什么原因导致的问题啊？

**Comment by lu-uux** [comment]
三楼正解

**Comment by zhwei4150** [comment]
@lu-uux 这个问题因为源码没有加载外部jar包所致吗？目前有解决方案吗？

**Comment by a49a** [comment]
现已解决
