### ISSUE TITLE
@yangsishu

### ISSUE THREAD

**Issue by taiziwang** [DTStack/flinkStreamSQL#194]
@yangsishu
 基于flinkStreamSQL1.8.1-dev,flink1.8.1,kakfa010,mysql5.6组件版本测试发现以下问题： 
yarnPer模式:
 a.kafka2mysql:
  sh sumbit异常日志: 
	   cloud not deploy yarn job cluster
	   diagnostics:exception from container-launch : Exception in thread "main" java.lang.unsupportedClassVersionError:org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint:Unsupport major.minor version52.0	
	   
  直接yarn run -c xxx 提交正常 
  
 b.kafka2kafka:
  直接yarn run -c xxx提交异常日志:   
   org.apache.flink.client.program.ProgramInvocationException:the program caused error:
   caused by java.lang.NoClassDefFoundError:org.apache.flink.api.common.ExceptionConfig$CloureCleanerLeavel
     org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducerBase.<init>
     org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer09.<init>
     org.apache.flink.streaming.connectors.kafka.FlinkKafkaProducer010.<init>

Local模式：
 kafka2mysql:
 Exception in thread "main" org.apache.flink.util.FlinkException: Cloud not create the dispatcherResourceManagerComponent
 caused by:java.net.BindException:cloud not start rest entrypoint on any port range 8081;
 后再MyLocalStreamEnvironment添加conf.add("rest.bind-port","8082")启动端口不冲突
 异常信息:
  job execution failed-->failed to construct kafka consumer--->caused by org.apache.kafka.common.kafkaException:org.apache.kafka
  .common.serialization.ByteArrayDeserialer is not instance of org.apache.kafka.common.serialization.Deserializer

standalone模式:
 kafka2mysql:
  sh sumbit异常日志: 
  Exception in thread "main" java.lang.IllegalStateExption: MiniCluster is not yet running
  主要来自ClusterClinetFactory.createStandoneClient问题
      
yarnPer 基于flink1.8kafka2kafka 问题处理优先更新推送，谢谢!

_Originally posted by @taiziwang in https://github.com/DTStack/flinkStreamSQL/issues/192#issuecomment-533040784_

**Comment by todd5167** [comment]
@taiziwang 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。
