### ISSUE TITLE
Flink1.8 yarn模式下运行，提示plugin missing，但是已经在yarn的各个节点相同的路径下放了plugin，麻烦问下是什么问题

### ISSUE THREAD

**Issue by qiuqingyu** [DTStack/flinkStreamSQL#195]
```
file: '/data/yarn/nm/usercache/**/appcache/application_1568880190912_0012/blobStore-1ea851c3-9bbd-4b59-b79a-8137c08ea830/job_95d313d74b8db2dc618ad32e28049575/blob_p-e655533573dd984916a97683812280828edda0eb-93ec5e7ef29178743e6163f263cd960b' (valid JAR)
    file: '/home/**/flinkStreamSQL/plugins/kafka11source/kafka11-source-v1.8.0_dev.jar' (missing)
    file: '/home/**/flinkStreamSQL/plugins/kafka11sink/kafka11-sink-v1.8.0_dev.jar' (missing)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperator(StreamConfig.java:236)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:104)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:269)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.dtstack.flink.sql.source.kafka.CustomerKafka011Consumer
```
@yangsishu

**Comment by yangsishu** [comment]
目录不能是/**/ 这个

**Comment by qiuqingyu** [comment]
> 目录不能是/**/ 这个

额...这个是我把文件夹名字给故意删掉了，用**代替的

**Comment by todd5167** [comment]
@qiuqingyu 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

**Comment by qiuqingyu** [comment]
> @qiuqingyu 新推了一版本1.8_dev可以在试试，需要拷贝flink-table-common-1.8.1.jar和flink-table-planner_2.11-1.8.1.jar到flinklib下。

不好意思，我今天试了下，报错还是和之前一样，提示plugin找不到，报错信息和之前一样

**Comment by qiuqingyu** [comment]
@yangsishu @todd5167 这是我提交的完整配置，麻烦看下，我把plugin插件拷贝到了各个节点的相同目录下
sh bin/submit.sh -sql /home/v11103357/flinkStreamSQL/test.sql -name test -localSqlPluginPath /home/v11103357/flinkStreamSQL/plugins -mode yarn -remoteSqlPluginPath /home/v11103357/flinkStreamSQL/plugins -flinkconf /home/v11103357/flink-1.8.2/conf -yarnconf /etc/hadoop/conf -confProp {"time.characteristic":"EventTime","sql.checkpoint.interval":10000} -flinkJarPath /home/v11103357/flink-1.8.2/lib
使用的是CDH集群

**Comment by qiuqingyu** [comment]
@yangsishu @todd5167

**Comment by taiziwang** [comment]
@qiuqingyu   你可以尝试把kafka11-source和sink. jar拷贝放到flinklib下看看 这样肯定可以加载成功的

**Comment by dingyj** [comment]
我试了，可以
