### ISSUE TITLE
如何处理删除数据的情况

### ISSUE THREAD

**Issue by ambitiuosDRX** [DTStack/flinkStreamSQL#198]
现在有这么一个场景：我需要读取MySQL里的一个表数据，然后把数据Sink到Es中。
MySQL的表名是 student，里面有三个字段 id ，name，age;
我使用canel处理binlog，然后将数据打到Kafka里，然后使用flinkStreamSQL框架写SQL
CREATE TABLE MyTable(
  id int,
  name string,
  age int
 )WITH(
    type ='kafka10',
    bootstrapServers ='localhost:9092',
    offsetReset ='latest',
    topic ='testtopic',
    parallelism ='1'
 );
 
CREATE TABLE MyResult(
  id int,
  name string,
  age int
 )WITH(
    type ='elasticsearch',
    address ='localhost:9300',
    cluster='dahai-product',
    estype ='mytype',
    index ='flink2es',
    id ='0',
    parallelism ='1'
 );
insert into MyResult  select  id,name,age from MyTable;

问题：如果我在数据库的student表中删除了一条数据，这种情况如何处理？

**Comment by yangsishu** [comment]
不能物理删除，要加个字段做逻辑删除；
