### ISSUE TITLE
有没有roadmap把flink CEP集成到sql里面

### ISSUE THREAD

**Issue by hongtao12310** [DTStack/flinkStreamSQL#20]

**Comment by yangsishu** [comment]
这个暂时还没有这计划

**Comment by yangsishu** [comment]
你也可以说说你的需求

**Comment by hongtao12310** [comment]
比如在做用户画像 风控等领域 会有很多规则应用 

看到阿里云flink已经集成CEP到flink sql query 语句
https://help.aliyun.com/document_detail/73845.html?spm=a2c4g.11186623.6.637.598ba182RQXEGA

**Comment by yangsishu** [comment]
这个已经在我们的开发计划里了，但是具体时间不定
