### ISSUE TITLE
kafka不支持嵌套json啊

### ISSUE THREAD

**Issue by AccordwangAccord** [DTStack/flinkStreamSQL#203]
这种的嵌套就不支持:
{"a":[{"name":"eee","addr":"jiangsu","b":[{"code":"123","shop_id":"123"},{"code":"234","shop_id":"245"}]}],"gmt_create":"2019-10-09","store_id":"567"}

**Comment by yangsishu** [comment]
支持的

**Comment by yangsishu** [comment]
https://github.com/DTStack/flinkStreamSQL/pull/129

**Comment by AccordwangAccord** [comment]
@yangsishu  最早的哪个分支支持的，因为我现在一直用的你的1.51的分支开发的，你现在的master我用不上。谢谢告知

**Comment by AccordwangAccord** [comment]
@yangsishu 
这种的嵌套怎么不支持啊？试过了获取不到啊a[0].name:
{"a":
[
 {"name":"eee","addr":"jiangsu",
    "b":
         [
		 {"code":"123","shop_id":"123"},
		 {"code":"234","shop_id":"245"}
		 ]
 }
]
,"gmt_create":"2019-10-09","store_id":"567"
}

**Comment by yangsishu** [comment]
贴下报错信息

**Comment by AccordwangAccord** [comment]
@yangsishu 没有报错啊，就是json数组这个字段打印出来都是null ,其他字段都有值
,现在亲测，嵌套的json对象可以解析，json数组不可以解析，a[0].name 这个解析出来的值为null

**Comment by todd5167** [comment]
@AccordwangAccord 1.5支持json数组的解析，1.8这个还没合过来

**Comment by AccordwangAccord** [comment]
@todd5167 
1.5的也是正则匹配有问题的
比如d[0].name VARCHAR AS name 正则就把d[0].name 截取成 name了
       a.b.c varchar as c 正则就把a.b.c截取成a.b.c(json嵌套的是对的)看下图:
![image](https://user-images.githubusercontent.com/50613385/66696164-24832900-ecfc-11e9-80f4-ce8f099ea93e.png)

**Comment by AccordwangAccord** [comment]
@todd5167 
![image](https://user-images.githubusercontent.com/50613385/66698664-543d2b80-ed12-11e9-831d-cc4eb76d7382.png)
数组的解析出来是错的，json对象解析出来是对的(比如a.b.c  解析出来的key就是a.b.c)
d[0].name  解析出来的key就是name不是 d[0].name
