### ISSUE TITLE
ES的参数可以指定账号+密码吗？

### ISSUE THREAD

**Issue by durixu2007** [DTStack/flinkStreamSQL#208]
您好，请问ES的参数可以指定账号+密码吗？我在文档里看到是没有指定账号+密码字段的。
![image](https://user-images.githubusercontent.com/1773928/67263892-01b2fa80-f4dc-11e9-934c-a8751a3570b5.png)

**Comment by yangsishu** [comment]
现在暂时不支持

**Comment by xiuzhu9527** [comment]
@ambitiuosDRX 现在支持了

**Comment by durixu2007** [comment]
谢谢老板及时支持！！！
