### ISSUE TITLE
本地idea 本地test测试提交yarn_pre报错，急，大神能否回答下，谢谢！

### ISSUE THREAD

**Issue by tianhuaxing** [DTStack/flinkStreamSQL#211]
报错：Log Type: jobmanager.err
Log Upload Time: Thu Nov 07 15:10:09 +0800 2019
Log Length: 99
Error: Could not find or load main class org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint

-------------------------------------------------------------------------------------------------------------
测试类：
    @Test
    public void submitYarnPreJob() throws Exception {
        FlinkOption option = new FlinkOption();
        option.setName("flink-deamo");
        option.setMode(ClusterMode.yarnPer);
        option.setFlinkconf("D:\\tmp\\flinkconf");
        option.setYarnconf("D:\\tmp\\yarnconf");
        option.setLocalSqlPluginPath("D:\\tmp\\plugins");
        option.setFlinkJarPath("D:\\tmp\\flinkconf\\lib");
        Configuration config = GlobalConfiguration.loadConfiguration(option.getFlinkconf());
        JobGraph jobGraph = PackagedProgramUtils.createJobGraph(new 
        FlinkOptionParser(option).getProgram(), config, 1);
        PerJobSubmitter.submit(option, jobGraph);
    }

D:\\tmp\\flinkconf 下有文件flink-conf.yaml

D:\\tmp\\yarnconf下有文件core-site.xml，hdfs-site.xml，yarn-site.xml，mapred-site.xml

D:\\tmp\\flinkconf\\lib下面有
flink-clients_2.11-1.8.0.jar

请问下本地测试跑standalone是可以提交得，但是跑yarn_pre就一直找不到类Could not find or load main class org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint报错，请问下什么原因？谢谢

**Comment by todd5167** [comment]
@tianhuaxing 1.8.0_release launcher有个测试类，可以参考里面的参数

**Comment by dakeleblack** [comment]
请问解决了吗
