### ISSUE TITLE
kafka json 映射 转义字符问题

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkStreamSQL#227]
{"deviceId":"'{\\\"deviceId\\\":\\\"fca014973f\\\",\\\"appId\\\":\\\"FaceSaaS_16E344F1A6B\\\",\\\"sdkVersion\\\":\\\"v1.0\\\",\\\"detectVersion\\\":\\\"1\\\",\\\"identifyVersion\\\":\\\"12\\\",\\\"action\\\":\\\"detectFace\\\",\\\"content\\\":\\\"not found\\\",\\\"cost\\\":0,\\\"total\\\":17694,\\\"timestamp\\\":1574418177700,\\\"totalRAM\\\":2019868,\\\"usedRAM(percent)\\\":\\\"40%\\\",\\\"curProcessCpuRate\\\":3.90625}'"}

数据是这样的怎么映射

**Comment by oliveryunchang** [comment]
现在我是，以字符串读取，然后编写UDF：将字符串格式化成json，提取属性值

**Comment by maidou75293** [comment]
> 现在我是，以字符串读取，然后编写UDF：将字符串格式化成json，提取属性值

就是自己写UDF提取呗

**Comment by maidou75293** [comment]
改了你们源码 兼容 不规范json

**Comment by todd5167** [comment]
@maidou75293  不规范json比较适合用udf来解析，毕竟每个业务场景不同。
