### ISSUE TITLE
elasticsearch 6.X是否支持啊 兄弟

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkStreamSQL#228]

**Comment by xiuzhu9527** [comment]
目前还不支持

**Comment by maidou75293** [comment]
升级到6 成本高吗



---原始邮件---
发件人: "xiuzhu9527"<notifications@github.com&gt;
发送时间: 2019年11月23日(星期六) 中午11:25
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkStreamSQL] elasticsearch 6.X是否支持啊 兄弟 (#228)



目前还不支持

**Comment by xiuzhu9527** [comment]
升级成本不高

**Comment by maidou75293** [comment]
我改了源码&nbsp; 支持6.1.3 对接你们的 flink sql



---原始邮件---
发件人: "xiuzhu9527"<notifications@github.com&gt;
发送时间: 2019年11月23日(星期六) 中午11:25
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkStreamSQL] elasticsearch 6.X是否支持啊 兄弟 (#228)



目前还不支持

**Comment by todd5167** [comment]
@maidou75293   可以推过来

**Comment by maidou75293** [comment]
推到哪个分之?



---原始邮件---
发件人: "todd5167"<notifications@github.com&gt;
发送时间: 2019年12月6日(星期五) 晚上9:39
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkStreamSQL] elasticsearch 6.X是否支持啊 兄弟 (#228)



@maidou75293   可以推过来

**Comment by maidou75293** [comment]
OK



---原始邮件---
发件人: "todd5167"<notifications@github.com&gt;
发送时间: 2019年12月6日(星期五) 晚上9:39
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkStreamSQL] elasticsearch 6.X是否支持啊 兄弟 (#228)



@maidou75293   可以推过来

**Comment by maidou75293** [comment]
写 hive&nbsp; 支持 parquet吗



---原始邮件---
发件人: "todd5167"<notifications@github.com&gt;
发送时间: 2019年12月6日(星期五) 晚上9:39
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkStreamSQL] elasticsearch 6.X是否支持啊 兄弟 (#228)



@maidou75293   可以推过来

**Comment by a49a** [comment]
已支持
