### ISSUE TITLE
有使用cep的demo吗

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkStreamSQL#230]

**Comment by zuoqiaoliang** [comment]
官网上例子很多，贴个测试通过的。 insert
into
    MyResultTable
    SELECT T.aid, T.bid, T.cid
FROM MyTable
MATCH_RECOGNIZE (
  ORDER BY PROCTIME
  MEASURES
    A.id AS aid,
    B.id AS bid,
    C.id AS cid
  PATTERN (A B C)
  DEFINE
    A AS A.name = 'a',
    B AS B.name = 'b',
    C AS C.name = 'c'
) AS T;

**Comment by chaozwn** [comment]
能贴一下建表语句吗

**Comment by chaozwn** [comment]
> 官网上例子很多，贴个测试通过的。 insert
> into
> MyResultTable
> SELECT T.aid, T.bid, T.cid
> FROM MyTable
> MATCH_RECOGNIZE (
> ORDER BY PROCTIME
> MEASURES
> A.id AS aid,
> B.id AS bid,
> C.id AS cid
> PATTERN (A B C)
> DEFINE
> A AS A.name = 'a',
> B AS B.name = 'b',
> C AS C.name = 'c'
> ) AS T;

能贴下建表语句吗

**Comment by chaozwn** [comment]
> 官网上例子很多，贴个测试通过的。 insert
> into
> MyResultTable
> SELECT T.aid, T.bid, T.cid
> FROM MyTable
> MATCH_RECOGNIZE (
> ORDER BY PROCTIME
> MEASURES
> A.id AS aid,
> B.id AS bid,
> C.id AS cid
> PATTERN (A B C)
> DEFINE
> A AS A.name = 'a',
> B AS B.name = 'b',
> C AS C.name = 'c'
> ) AS T;

我如何指定字段作为eventtime

**Comment by a49a** [comment]
EventTime 指定语句如下： 
WATERMARK FOR colName AS withOffset( colName , delayTime )

可以参考下文档：
https://github.com/DTStack/flinkStreamSQL/blob/1.8_release/docs/plugin/kafkaSource.md
