### ISSUE TITLE
hbase修改后:分割的问题并没有解决

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkStreamSQL#231]
@Override
    public HbaseSink genStreamSink(TargetTableInfo targetTableInfo) {
        HbaseTableInfo hbaseTableInfo = (HbaseTableInfo) targetTableInfo;
        this.zookeeperQuorum = hbaseTableInfo.getHost();
        this.port = hbaseTableInfo.getPort();
        this.parent = hbaseTableInfo.getParent();
        this.tableName = hbaseTableInfo.getTableName();
        this.rowkey = hbaseTableInfo.getRowkey();
        this.columnNameFamily = hbaseTableInfo.getPhysicalFields();
        return this;
    }

这样改，最后一个参数

**Comment by chaozwn** [comment]
然后finish的代码照着改一下，就可以用了hbase

**Comment by yangsishu** [comment]
@zoudaokoulife

**Comment by oliveryunchang** [comment]
我把DDL语法调整成这样，不改最后一个参数也可以正常使用
```
CREATE TABLE MyResult(
    cf:channel varchar,
    cf:pv BIGINT
 )WITH(
    type ='hbase',
    zookeeperQuorum ='rdos1:2181',
    tableName ='workerinfo',
    rowKey ='channel',
    parallelism ='1',
    zookeeperParent ='/hbase'
 )

INSERT INTO MyResult
SELECT
  'channel' AS channel,
  1 AS pv
  FROM
   t
GROUP BY ...;

 ```

**Comment by chaozwn** [comment]
你这样没有考虑到如果有不同列簇，有相同的列的情况，我认为列簇:列名 as 的语法还是需要的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Oliver 云长"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 晚上9:45
收件人:&nbsp;"DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送:&nbsp;"No.1"<326747337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkStreamSQL] hbase修改后:分割的问题并没有解决 (#231)




我把DDL语法调整成这样，不改最后一个参数也可以正常使用
 CREATE TABLE MyResult(     cf:channel varchar,     cf:pv BIGINT  )WITH(     type ='hbase',     zookeeperQuorum ='rdos1:2181',     tableName ='workerinfo',     rowKey ='channel',     parallelism ='1',     zookeeperParent ='/hbase'  ) INSERT INTO MyResult SELECT   'channel' AS channel,   1 AS pv   FROM    t GROUP BY ...;

**Comment by oliveryunchang** [comment]
那你那边的语法是怎样的？

**Comment by chaozwn** [comment]
假如这种情况 person:name,network:name,下面的语法怎么区分name呢

**Comment by chaozwn** [comment]
> 那你那边的语法是怎样的？

假如这种情况 person:name,network:name,下面的语法怎么区分name呢

**Comment by chaozwn** [comment]
重命名之后原来的列簇和列可以通过pysicalfield来获取




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Oliver 云长"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月9日(星期四) 晚上9:45
收件人:&nbsp;"DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;;
抄送:&nbsp;"No.1"<326747337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkStreamSQL] hbase修改后:分割的问题并没有解决 (#231)




我把DDL语法调整成这样，不改最后一个参数也可以正常使用
 CREATE TABLE MyResult(     cf:channel varchar,     cf:pv BIGINT  )WITH(     type ='hbase',     zookeeperQuorum ='rdos1:2181',     tableName ='workerinfo',     rowKey ='channel',     parallelism ='1',     zookeeperParent ='/hbase'  ) INSERT INTO MyResult SELECT   'channel' AS channel,   1 AS pv   FROM    t GROUP BY ...;

**Comment by chaozwn** [comment]
假如这种情况 person:name,network:name,下面的语法怎么区分name呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Oliver 云长"<notifications@github.com&gt;; 
发送时间: 2020年1月9日(星期四) 晚上9:48
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com&gt;; 
抄送: "No.1"<326747337@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DTStack/flinkStreamSQL] hbase修改后:分割的问题并没有解决 (#231)




那你那边的语法是怎样的？

**Comment by oliveryunchang** [comment]
非常感谢，明白你说的场景，但是现在看[Hbase输出源](https://github.com/DTStack/flinkStreamSQL/blob/1.8.0_release/docs/hbaseSink.md)的文档并没有写在SELECT语句中的用法，不知道你那边能不能提供SQL DDL和SELECT的示例

**Comment by chaozwn** [comment]
create table kafka11SourceTable(
acct varchar,
money double,
xctime varchar
)with(
type='kafka11',
bootstrapServers='hadoop102:9092,hadoop103:9092,hadoop104:9092',
zookeeperQuorum='hadoop102:2181,hadoop103:2181,hadoop104:2181',
offsetReset='latest',
groupId='csin_stream',
topic='csin_source',
parallelism='1'
);

CREATE TABLE hbaseResultTable(
    person:acct varchar,
    person:money double,
    network:acct varchar,
    time:xctime varchar
 )WITH(
    type ='hbase',
    zookeeperQuorum ='hadoop102:2181,hadoop103:2181,hadoop104:2181',
    zookeeperParent ='/hbase',
    tableName ='csin_test:hbaseResultTable',
    rowKey ='acct',
    parallelism ='1'
);

insert into hbaseResultTable
select acct,money,acct,xctime from kafka11SourceTable;

**Comment by chaozwn** [comment]
> 非常感谢，明白你说的场景，但是现在看[Hbase输出源](https://github.com/DTStack/flinkStreamSQL/blob/1.8.0_release/docs/hbaseSink.md)的文档并没有写在SELECT语句中的用法，不知道你那边能不能提供SQL DDL和SELECT的示例

CREATE TABLE hbaseResultTable(
    person:acct varchar as person_acct,
    person:money double as person_money,
    network:acct varchar as network_acct,
    time:xctime varchar as person_xctime
 )WITH(
    type ='hbase',
    zookeeperQuorum ='hadoop102:2181,hadoop103:2181,hadoop104:2181',
    zookeeperParent ='/hbase',
    tableName ='csin_test:hbaseResultTable',
    rowKey ='acct',
    parallelism ='1'
);

我这边建议使用这样的语法，我们可以从this.columnNameFamily = hbaseTableInfo.getPhysicalFields(); 后的原来的列名，用来切割，只不过要注意下排序问题，用linkedmap，就可以解决这个问题，我可以代替修改，提交修改后的代码

**Comment by oliveryunchang** [comment]
手动点赞

**Comment by chaozwn** [comment]
> 手动点赞

需要我提交代码吗，怎么提交

**Comment by oliveryunchang** [comment]
> 
> 
> > 手动点赞
> 
> 需要我提交代码吗，怎么提交

那就得走袋鼠云他们的PR提交流程了，我也没提交过，可以问问他们，不过我本地按照你这个模式，把代码调通了

**Comment by a49a** [comment]
FlinkX 1.12 已经解决类似问题
