### ISSUE TITLE
请问支持多层left join 吗

### ISSUE THREAD

**Issue by wenbaoup** [DTStack/flinkStreamSQL#236]
insert into  categorysalemode_realtime_hh
  select 
		 b.periodid
		,gp.groupid    as  categorygroupid
		,s.salemodecategoryid  as salemodecategroyid
		,c.mode        as  citymodeid
		,b.type         as typeid
		,sum(b.amount) as amount
		,sum(b.payamount) as payamount
		,sum(b.ratioamount) as ratioamount
		,sum(b.ratiopayamount) as ratiopayamount
		,sum(b.statisticspackagecount) as statisticspackagecount
        ,'dm_order_categorysalemode_realtime_hh' as tablename
	from bizuser_realtime_hh b  
	left join city c  on b.cityid=c.id 
	left join etl_categorygroup gp on gp.categoryid=b.firstcategoryid
	left join salemode s  on s.salemodeid=b.itemproductsalemode
	where gp.productcategorygroupmanagementid=1 and  s.isvalid=1
	group by b.periodid ,c.mode,gp.groupid,s.salemodecategoryid,b.type;
	
运行到getTableFromCache方法是报not register table

**Comment by todd5167** [comment]
@wenbaoup   支持的，你发下完整sql吧

**Comment by wenbaoup** [comment]
拉了最新的代码 是支持的
