### ISSUE TITLE
kafka ddl 如何指定 发送到kafka 中的key

### ISSUE THREAD

**Issue by wangbaoliang** [DTStack/flinkStreamSQL#237]
请问如何在sink kafka ddl 里面指定发送到kafka中的key  
KeyedSerializationSchemaWrapper

**Comment by todd5167** [comment]
@wangbaoliang 暂时不支持指定分区Key。KeyedSerializationSchemaWrapper只实现了serializeValue方法，如果需要根据某一字段的数据分配partition，需要实现FlinkKafkaPartitioner接口方法。

**Comment by zoudaokoulife** [comment]
@wangbaoliang 这个我们是需要的。如果你有兴趣开发对应的功能并贡献是最好的。
