### ISSUE TITLE
table别名BUG提交

### ISSUE THREAD

**Issue by liubin2048** [DTStack/flinkStreamSQL#240]
分支：1.8.0_release

com.dtstack.flink.sql.side.SideSQLParser

        if (leftTbAlias.equals("")){
            tableInfo.setRightTableAlias(rightTableName);
        } else {
            tableInfo.setRightTableAlias(rightTableAlias);
        }

改成if ("".equals(rightTableAlias)){

**Comment by todd5167** [comment]
@liubin2048  最新代码内部已经修复了，感谢
