### ISSUE TITLE
postgresql isUpsert 不生效

### ISSUE THREAD

**Issue by panzhenyu12** [DTStack/flinkStreamSQL#243]
设置了 isUpsert =true, keyField ='order_no',但是没有生效，生产的sql不带ON conflict(),在buildInsertSql打印this.isUpsert为false,keyField是null。

**Comment by todd5167** [comment]
@panzhenyu12   感谢。我们内部先复现下，修复后再推出来

**Comment by panzhenyu12** [comment]
@todd5167 不好意思，我的原因， isUpsert =true 忘记加了''，导致出错~
