### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: path /opt/test/plugins/oraclesource not exists!!!

### ISSUE THREAD

**Issue by tonyC2016** [DTStack/flinkStreamSQL#247]
![image](https://user-images.githubusercontent.com/18416187/71649989-14ed0c80-2d4e-11ea-8274-dcedea0a2585.png)
维表和目标都是oracle的情况下会解析错误

**Comment by todd5167** [comment]
@tonyC2016 检查下plugins是否有插件包
