### ISSUE TITLE
addSink默认逐条读逐条写

### ISSUE THREAD

**Issue by AccordwangAccord** [DTStack/flinkStreamSQL#251]
逐条插入性能肯定会成为瓶颈，五六十万条记录不可能发送五六十万条insert into语句给数据库.
.可以批次写吗？我看hbase的都是逐条写的

**Comment by todd5167** [comment]
@AccordwangAccord  rdb可以批量插入，通过batchSize进行配置，hbasesink暂时还没弄批量写

**Comment by hengyuan** [comment]
@todd5167 我理解hbase改成批量写也很容易。在HbaseOutputFormat中做一个计数器，满多少条调用一次批量put函数：table.put(List<put>); 这样做是有什么缺陷吗？

**Comment by hengyuan** [comment]
hbasesink的批量写我认为是要这样实现吧？请赐教！

**Comment by hengyuan** [comment]
需要设置一个时间和条数，哪个先到了，就应该批量刷写，不然会造成不够设置条数的数据刷写不出去

**Comment by hengyuan** [comment]
hbase的批量写应该使用缓存快的方式进行批量写入，可以减少rpc

**Comment by todd5167** [comment]
@hengyuan   flink hbase连接器用的就是批量和定时，这个部分后续会优化下。
