### ISSUE TITLE
kafkaSink经过groupby默认会输出两条数据是什么情况

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkStreamSQL#253]
![image](https://user-images.githubusercontent.com/51357674/72697826-54a05a80-3b7c-11ea-8f8e-01f3617c7a8e.png)
为什么会有两条数据输出

**Comment by chaozwn** [comment]
![1579492835919](https://user-images.githubusercontent.com/51357674/72697863-874a5300-3b7c-11ea-9da4-1c2e78dcc0ef.jpg)

**Comment by todd5167** [comment]
@chaozwn   之前未过滤回撤流，新发的版本过滤了

**Comment by chaozwn** [comment]
> @chaozwn 之前未过滤回撤流，新发的版本过滤了

怎么版本又还原回来了，而且现在还是有两条数据

**Comment by todd5167** [comment]
@chaozwn  这个修复放到后续的分支上了

**Comment by chaozwn** [comment]
> @chaozwn 这个修复放到后续的分支上了

现在这个版本，有没有快速解决的方法

**Comment by chaozwn** [comment]
> @chaozwn 之前未过滤回撤流，新发的版本过滤了

我想直接用你发的那个版本，那个版本目前有啥问题

**Comment by hengyuan** [comment]
你做一下数据的过滤就行了，把false的过滤掉
