### ISSUE TITLE
新版kafka无法正常使用

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkStreamSQL#254]
create table kafka11SourceTable(
acct varchar,
money double,
xctime varchar
)with(
type='kafka11',
bootstrapServers='hadoop102:9092,hadoop103:9092,hadoop104:9092',
zookeeperQuorum='hadoop102:2181,hadoop103:2181,hadoop104:2181',
offsetReset='latest',
groupId='csin_stream',
topic='csin_source',
parallelism='1'
);

create table kafka11SinkTable(
acct varchar,
money double,
xctime varchar
)with(
type='kafka11',
bootstrapServers='hadoop102:9092,hadoop103:9092,hadoop104:9092',
topic='csin_source2',
parallelism='1'
);

insert into kafka11SinkTable select acct, sum(money) as money, max(xctime) as xctime from kafka11SourceTable group by acct;

**Comment by todd5167** [comment]
@chaozwn  什么错误

**Comment by a49a** [comment]
Kafka目前正常使用
