### ISSUE TITLE
github 样例SQL Idea 本地调式错误

### ISSUE THREAD

**Issue by cgqfzy** [DTStack/flinkStreamSQL#259]
### 拿 项目 README 样例在 IDEA 中调试报错
* 1 错误如下

```java
Exception in thread "main" java.lang.RuntimeException: 不支持 //自定义的函数 类型
	at com.dtstack.flink.sql.util.ClassUtil.stringConvertClass(ClassUtil.java:92)
	at com.dtstack.flink.sql.table.AbsTableParser.dbTypeConvertToJavaType(AbsTableParser.java:121)
	at com.dtstack.flink.sql.table.AbsTableParser.parseFieldsInfo(AbsTableParser.java:101)
	at com.dtstack.flink.sql.source.kafka.table.KafkaSourceParser.getTableInfo(KafkaSourceParser.java:79)
	at com.dtstack.flink.sql.table.TableInfoParser.parseWithTableType(TableInfoParser.java:104)
	at com.dtstack.flink.sql.parser.SqlParser.parseSql(SqlParser.java:116)
	at com.dtstack.flink.sql.Main.main(Main.java:134)
	at com.dtstack.flink.sql.launcher.LauncherMain.main(LauncherMain.java:84)
```

* 2 样例代码中用函数定义了字段

```sql
CREATE TABLE MyTable(
    name varchar,
    channel varchar,
    pv int,
    xctime bigint,
    CHARACTER_LENGTH(channel) AS timeLeng //自定义的函数
 )WITH(
    type ='kafka09',
    bootstrapServers ='172.16.8.198:9092',
    zookeeperQuorum ='172.16.8.198:2181/kafka',
    offsetReset ='latest',
    topic ='nbTest1',
    parallelism ='1'
 );

```

* 3 跟踪代码到 AbsTableParser#parseFieldsInfo 

```java

public void parseFieldsInfo(String fieldsInfo, TableInfo tableInfo){

        List<String> fieldRows = DtStringUtil.splitIgnoreQuota(fieldsInfo, ',');
        for(String fieldRow : fieldRows){
            fieldRow = fieldRow.trim();

            String[] filedInfoArr = fieldRow.split("\\s+");
            if(filedInfoArr.length < 2 ){
                throw new RuntimeException(String.format("table [%s] field [%s] format error.", tableInfo.getName(), fieldRow));
            }

            boolean isMatcherKey = dealKeyPattern(fieldRow, tableInfo);
            if(isMatcherKey){
                continue;
            }

            //Compatible situation may arise in space in the fieldName
            String[] filedNameArr = new String[filedInfoArr.length - 1];
            System.arraycopy(filedInfoArr, 0, filedNameArr, 0, filedInfoArr.length - 1);
            String fieldName = String.join(" ", filedNameArr);
            String fieldType = filedInfoArr[filedInfoArr.length - 1 ].trim();
            Class fieldClass = dbTypeConvertToJavaType(fieldType);

            tableInfo.addPhysicalMappings(filedInfoArr[0],filedInfoArr[0]);
            tableInfo.addField(fieldName);
            tableInfo.addFieldClass(fieldClass);
            tableInfo.addFieldType(fieldType);
            tableInfo.addFieldExtraInfo(null);
        }

        tableInfo.finish();
    }


```

这里解析定义字段的方式比较简单, 空格分隔，取 第一个单词 字段名称,第二个单词 为 字段类型，这里对于 上述 用函数定的字段不适用，并没有看到针对函数的处理，这里就比较困惑了，其它同学是怎么提交上去的？

还是我追踪代码位置不对？

求助！！

**Comment by yangsishu** [comment]
自定义函数 sql里面需要加 CREATE (scala|table|aggregate) FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;

**Comment by yangsishu** [comment]
原生flink建表语句是不支持加函数的，flinkstreamsql做了一层转化

**Comment by cgqfzy** [comment]
> 自定义函数 sql里面需要加 CREATE (scala|table|aggregate) FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;

这句话也是有的 ，完整的输入代码

```sql
CREATE scala FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;


CREATE TABLE MyTable(
    name varchar,
    channel varchar,
    pv int,
    xctime bigint,
    CHARACTER_LENGTH(channel) AS timeLeng //自定义的函数
 )WITH(
    type ='kafka09',
    bootstrapServers ='172.16.8.198:9092',
    zookeeperQuorum ='172.16.8.198:2181/kafka',
    offsetReset ='latest',
    topic ='nbTest1',
    parallelism ='1'
 );

CREATE TABLE MyResult(
    channel varchar,
    pv varchar
 )WITH(
    type ='mysql',
    url ='jdbc:mysql://172.16.8.104:3306/test?charset=utf8',
    userName ='dtstack',
    password ='abc123',
    tableName ='pv2',
    parallelism ='1'
 );

CREATE TABLE workerinfo(
    cast(logtime as TIMESTAMP) AS rtime,
    cast(logtime) AS rtime
 )WITH(
    type ='hbase',
    zookeeperQuorum ='rdos1:2181',
    tableName ='workerinfo',
    rowKey ='ce,de',
    parallelism ='1',
    zookeeperParent ='/hbase'
 );

CREATE TABLE sideTable(
    cf:name varchar as name,
    cf:info varchar as info,
    PRIMARY KEY(name),
    PERIOD FOR SYSTEM_TIME //维表标识
 )WITH(
    type ='hbase',
    zookeeperQuorum ='rdos1:2181',
    zookeeperParent ='/hbase',
    tableName ='workerinfo',
    cache ='LRU',
    cacheSize ='10000',
    cacheTTLMs ='60000',
    parallelism ='1'
 );

insert
into
    MyResult
    select
        d.channel,
        d.info
    from
        (      select
            a.*,b.info
        from
            MyTable a
        join
            sideTable b
                on a.channel=b.name
        where
            a.channel = 'xc2'
            and a.pv=10      ) as d


```

**Comment by cgqfzy** [comment]
> > 自定义函数 sql里面需要加 CREATE (scala|table|aggregate) FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;
> 
> 这句话也是有的 ，完整的输入代码
> 
> ```sql
> CREATE scala FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;
> 
> 
> CREATE TABLE MyTable(
>     name varchar,
>     channel varchar,
>     pv int,
>     xctime bigint,
>     CHARACTER_LENGTH(channel) AS timeLeng //自定义的函数
>  )WITH(
>     type ='kafka09',
>     bootstrapServers ='172.16.8.198:9092',
>     zookeeperQuorum ='172.16.8.198:2181/kafka',
>     offsetReset ='latest',
>     topic ='nbTest1',
>     parallelism ='1'
>  );
> 
> CREATE TABLE MyResult(
>     channel varchar,
>     pv varchar
>  )WITH(
>     type ='mysql',
>     url ='jdbc:mysql://172.16.8.104:3306/test?charset=utf8',
>     userName ='dtstack',
>     password ='abc123',
>     tableName ='pv2',
>     parallelism ='1'
>  );
> 
> CREATE TABLE workerinfo(
>     cast(logtime as TIMESTAMP) AS rtime,
>     cast(logtime) AS rtime
>  )WITH(
>     type ='hbase',
>     zookeeperQuorum ='rdos1:2181',
>     tableName ='workerinfo',
>     rowKey ='ce,de',
>     parallelism ='1',
>     zookeeperParent ='/hbase'
>  );
> 
> CREATE TABLE sideTable(
>     cf:name varchar as name,
>     cf:info varchar as info,
>     PRIMARY KEY(name),
>     PERIOD FOR SYSTEM_TIME //维表标识
>  )WITH(
>     type ='hbase',
>     zookeeperQuorum ='rdos1:2181',
>     zookeeperParent ='/hbase',
>     tableName ='workerinfo',
>     cache ='LRU',
>     cacheSize ='10000',
>     cacheTTLMs ='60000',
>     parallelism ='1'
>  );
> 
> insert
> into
>     MyResult
>     select
>         d.channel,
>         d.info
>     from
>         (      select
>             a.*,b.info
>         from
>             MyTable a
>         join
>             sideTable b
>                 on a.channel=b.name
>         where
>             a.channel = 'xc2'
>             and a.pv=10      ) as d
> ```

看起来是注释不对，谢谢

**Comment by cgqfzy** [comment]
> > 自定义函数 sql里面需要加 CREATE (scala|table|aggregate) FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;
> 
> 这句话也是有的 ，完整的输入代码
> 
> ```sql
> CREATE scala FUNCTION CHARACTER_LENGTH WITH com.dtstack.Kun;
> 
> 
> CREATE TABLE MyTable(
>     name varchar,
>     channel varchar,
>     pv int,
>     xctime bigint,
>     CHARACTER_LENGTH(channel) AS timeLeng //自定义的函数
>  )WITH(
>     type ='kafka09',
>     bootstrapServers ='172.16.8.198:9092',
>     zookeeperQuorum ='172.16.8.198:2181/kafka',
>     offsetReset ='latest',
>     topic ='nbTest1',
>     parallelism ='1'
>  );
> 
> CREATE TABLE MyResult(
>     channel varchar,
>     pv varchar
>  )WITH(
>     type ='mysql',
>     url ='jdbc:mysql://172.16.8.104:3306/test?charset=utf8',
>     userName ='dtstack',
>     password ='abc123',
>     tableName ='pv2',
>     parallelism ='1'
>  );
> 
> CREATE TABLE workerinfo(
>     cast(logtime as TIMESTAMP) AS rtime,
>     cast(logtime) AS rtime
>  )WITH(
>     type ='hbase',
>     zookeeperQuorum ='rdos1:2181',
>     tableName ='workerinfo',
>     rowKey ='ce,de',
>     parallelism ='1',
>     zookeeperParent ='/hbase'
>  );
> 
> CREATE TABLE sideTable(
>     cf:name varchar as name,
>     cf:info varchar as info,
>     PRIMARY KEY(name),
>     PERIOD FOR SYSTEM_TIME //维表标识
>  )WITH(
>     type ='hbase',
>     zookeeperQuorum ='rdos1:2181',
>     zookeeperParent ='/hbase',
>     tableName ='workerinfo',
>     cache ='LRU',
>     cacheSize ='10000',
>     cacheTTLMs ='60000',
>     parallelism ='1'
>  );
> 
> insert
> into
>     MyResult
>     select
>         d.channel,
>         d.info
>     from
>         (      select
>             a.*,b.info
>         from
>             MyTable a
>         join
>             sideTable b
>                 on a.channel=b.name
>         where
>             a.channel = 'xc2'
>             and a.pv=10      ) as d
> ```

可能是这个注释不对， 我再看看 谢谢
