### ISSUE TITLE
用yarnPer模式提交时出现错误！

### ISSUE THREAD

**Issue by lijianfeng6666526** [DTStack/flinkStreamSQL#264]
提交命令如下:
sh submit.sh -sql /home/flinksql.txt  -name flinkstream  -remoteSqlPluginPath /home/FlinkStreamSQL1.8.0/plugins  -localSqlPluginPath /home/FlinkStreamSQL1.8.0/plugins  -mode yarnPer -flinkJarPath  /home/flinksql.jar -yarnconf  /home/hadoop-2.6.0/etc/hadoop  -flinkconf /home/flink-1.8.0/conf  -confProp \{\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000\}

查看nohup.out时，保以下错误
flink.sql. jauncher.perjob.Per JobClus terClientBuilder. createPerJobc lus terDescripton (Per JobClus terClientBui lder. java:83)

**Comment by todd5167** [comment]
@lijianfeng6666526  刚发布的最新代码吗

**Comment by lijianfeng6666526** [comment]
前一个月下载的------------------ 原始邮件 ------------------
发件人: "todd5167"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 下午4:49
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com>;
抄送: "lijianfeng6666526"<1015632409@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DTStack/flinkStreamSQL] 用yarnPer模式提交时出现错误！ (#264)



@lijianfeng6666526  刚发布的最新代码吗
 
&mdash;

**Comment by todd5167** [comment]
> 前一个月下载的


刚刚推送了一版，你拉下最新的代码试试看

**Comment by todd5167** [comment]
@lijianfeng6666526   你拉下最新的代码，再试试

**Comment by lijianfeng6666526** [comment]
好的------------------ 原始邮件 ------------------
发件人: "todd5167"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 下午4:56
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com>;
抄送: "lijianfeng6666526"<1015632409@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DTStack/flinkStreamSQL] 用yarnPer模式提交时出现错误！ (#264)


 
前一个月下载的
  
刚刚推送了一版，你拉下最新的代码试试看
 
&mdash;
