### ISSUE TITLE
窗口计算报org.apache.flink.table.api.ValidationException: Window can only be defined over a time attribute column.

### ISSUE THREAD

**Issue by LuoLaHansom** [DTStack/flinkStreamSQL#271]
我的sql：
CREATE TABLE MyTable(
    word varchar,
    ts timestamp,
    WATERMARK  FOR ts as withOffset(ts, 2000)
)WITH(	
	type='kafka11',
	bootstrapServers ='node01:9092',
	zookeeperQuorum ='node01:2181/kafka',
	offsetReset ='latest',
    topic ='test',
    parallelism ='1'
 );

CREATE TABLE MySink(
    window_start timestamp,
    window_end timestamp,
    word varchar,
    counts bigint
 )WITH(
    type ='console',
    parallelism ='1'
 );

Insert into MySink 
Select 
TUMBLE_START(ts, INTERVAL '3' SECOND) as window_start,
TUMBLE_END(ts, INTERVAL '3' SECOND) as window_end,
word,count(word) as counts from MyTable group by TUMBLE(ts, INTERVAL '3' SECOND), word;

然后在配置参数也配了事件时间，然后看源码也没解决问题，求助

**Comment by todd5167** [comment]
@LuoLaHansom  https://ci.apache.org/projects/flink/flink-docs-release-1.10/dev/table/sql/queries.html#group-windows

ROWTIME or PROCTIME

**Comment by LuoLaHansom** [comment]
@todd5167 是我的语法不对吗，我设置ts为rowtime

**Comment by zoudaokoulife** [comment]
ROWTIME 和PROCTIME 是内嵌到字段，在注册源表到时候注册到源表；你这边如果要用事件时间字段，把ts 替换为 ROWTIME 即可

**Comment by LuoLaHansom** [comment]
@zoudaokoulife 怎么改sql，抱歉，我不是很会

**Comment by LuoLaHansom** [comment]
已解决，改成
CREATE TABLE MyTable(
    word varchar,
    ts timestamp,
    WATERMARK  FOR ts as withOffset(ts, 2000)
)WITH(	
	type='kafka11',
	bootstrapServers ='node01:9092',
	zookeeperQuorum ='node01:2181/kafka',
	offsetReset ='latest',
    topic ='test',
    parallelism ='1'
 );

CREATE TABLE MySink(
    window_start timestamp,
    window_end timestamp,
    word varchar,
    counts bigint
 )WITH(
    type ='console',
    parallelism ='1'
 );

Insert into MySink 
Select 
TUMBLE_START(ROWTIME, INTERVAL '3' SECOND) as window_start,
TUMBLE_END(ROWTIME, INTERVAL '3' SECOND) as window_end,
word,count(word) as counts from MyTable group by TUMBLE(ROWTIME, INTERVAL '3' SECOND), word;
