### ISSUE TITLE
local模式下报错，上个版本可以运行，这个版本出问题了

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkStreamSQL#277]
![Snipaste_2020-03-14_11-49-22](https://user-images.githubusercontent.com/51357674/76674393-e9a65980-65e9-11ea-9e35-1badcf79b943.png)
![image](https://user-images.githubusercontent.com/51357674/76674386-caa7c780-65e9-11ea-997a-b07b6daac1f5.png)

**Comment by chaozwn** [comment]
create table kafka11SourceTable(
acct varchar,
money double,
xctime varchar
)with(
type='kafka11',
bootstrapServers='hadoop102:9092,hadoop103:9092,hadoop104:9092',
zookeeperQuorum='hadoop102:2181,hadoop103:2181,hadoop104:2181',
offsetReset='latest',
groupId='csin_stream',
topicIsPattern='false',
topic='csin_source',
parallelism='1'
);
你们topicIsPattern失去了默认值，导致createkafkatablesource。getpattern的时候是空

**Comment by chaozwn** [comment]
![image](https://user-images.githubusercontent.com/51357674/76674665-eeb8d800-65ec-11ea-9264-d68aa2bc4fad.png)
不设置值，就会给这个参数设置null

**Comment by chaozwn** [comment]
![image](https://user-images.githubusercontent.com/51357674/76674706-49eaca80-65ed-11ea-8733-a449c072518b.png)
修改下

**Comment by zoudaokoulife** [comment]
嗯。这个地方缺失了默认值，近期会推送一个修复版本。

**Comment by a49a** [comment]
已知问题，修复中
