### ISSUE TITLE
 能否把CLI模式改成yaml或者json输入模式

### ISSUE THREAD

**Issue by hongtao12310** [DTStack/flinkStreamSQL#28]
CLI输入经常会出错 特别是填写config properties的时候，能否改成配置的方式 
submit.sh config.yml / config.json

**Comment by hongtao12310** [comment]
另外还需要加入input validator ?比如指定mode 为yarn 那么yarnconf必须存在

**Comment by yangsishu** [comment]
这个后面会改掉

**Comment by yangsishu** [comment]
已经修改
