### ISSUE TITLE
支持apache pulsar的融合

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkStreamSQL#285]
1、近年来Pulsar日臻完善，从技术、架构、性能等综合方面大有取代kafka之势
2、大型互联网厂商已经大规模采用Pulsar作为基建
希望官方仔细评估pulsar的技术和架构，将产品能力针对Pulsar做一定的兼容和优化，包括性能和易用性

**Comment by yangsishu** [comment]
这个会考虑的
