### ISSUE TITLE
多表join

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkStreamSQL#286]
流表1，流表2，维表1，维表2 四表join可以支持吗？

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zoudaokoulife** [comment]
可以支持

**Comment by cmdares** [comment]
再问下，目前引擎是否通过命令或某种方式查看SQL的执行计划？

**Comment by a49a** [comment]
FlinkX 1.12 已支持
