### ISSUE TITLE
Flink1.10 和 FlinkStreamSQL的关系

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkStreamSQL#289]
通过学习近期Flink发布的版本，1.9 合并了 Blink，SQL能力大幅度增强，1.10 完善了大量的功能以及性能提升。想了解下Flink1.10 和 FlinkStreamSQL 目前的关系？
有点迷茫。
请专家给与解惑，当前的情况以及未来的走向与定位。
感谢！

**Comment by yangsishu** [comment]
FlinkStreamSQL是基于Flink做了一层更高级的分装，目的是为了更容易扩展源表，维表，结果表插件，在不修改flink源码的情况下；所以flink的功能FlinkStreamSQL 都支持的；Flink1.10 现在我们也在做兼容，近期会开源出去的；FlinkStreamSQL方向就是让flinksql开发更简单

**Comment by cmdares** [comment]
已知晓，感谢团队的辛勤付出！
期待版本尽快发布。
