### ISSUE TITLE
FlinkStreamSQL 与 Flinkx的关系

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkStreamSQL#290]
FlinkStreamSQL 与 Flinkx的关系是什么？是集成、取代还是配合的关系。
1、FlinkStreamSQL“结果表插件”和Flinkx的“写入插件”的关系，有重合也有不同？Flinkx更像Datax的流式版本。
2、FlinkStreamSQL 的source 只有Kafka，如果一个处理过程需要Mysq->kafka->FlinkStreamSQL->Es
这种数据流我们如何处理？是否要FlinkStreamSQL 与 Flinkx 配合使用?
Flinkx 将数据Mysql源头摄入Kafka，FlinkStreamSQL 进行转换，最后FlinkStreamSQL将数据写入Es。
如果是Mysq->kafka->FlinkStreamSQL->HDFS呢?
Flinkx 将数据Mysql源头摄入Kafka，FlinkStreamSQL 进行转换，最后Flinkx将数据写入HDFS。
我这理解对吗？
Flink定位是批流框架，那么FlinkStreamSQL 与 Flinkx 的关系，有点迷茫，目前是啥关系，未来定位又是这么样，请专家给与讲解。
感谢！

**Comment by yangsishu** [comment]
flinkx是解决数据同步的，flinkstreamsql是做实时计算的，没有关系

**Comment by cmdares** [comment]
@yangsishu 您好，还得再问下，FlinkX摄入到kafka中的数据，FlinkStreamSQL能否直接使用？

**Comment by zoudaokoulife** [comment]
可以的。只要满足输出到kafka的是json，avro，csv即可
