### ISSUE TITLE
kafkaSource 数据格式是否可以支撑avro

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkStreamSQL#294]
如题：Kafka中的接入数据源为avro的情况下，平台是否能够方便的提供这种格式的解析。
相关的文档：https://www.jianshu.com/p/e82f9c6c95ab
备注： Confluent平台的Ksql和整个生态基本默认是用avro作为高性能结构化的信息载体。
（Kafka 创始人团队的产品，当时使用过，还是要赞的。团队可以吸取下他们的经验，以便继续提高 flinkStreamSQL）
希望团队多考察下，看看是否有必要支撑avro。
感谢！

**Comment by zoudaokoulife** [comment]
当前推送版本是可以支持avro格式的。之前文档内容比较老旧。最近在重新编写新的文档。整理好之后会更新一次。
现在你可以查阅com.dtstack.flink.sql.sink.kafka.AbstractKafkaProducerFactory 这块代码来参考

**Comment by cmdares** [comment]
希望文档能够尽快升级到和版本匹配。以便将所有特性和功能对标。
OK，感谢！
