### ISSUE TITLE
求助！当我使用per job 的模式提交任务时 不能通过，但是yarn-session

### ISSUE THREAD

**Issue by 13691432320** [DTStack/flinkStreamSQL#295]

**Comment by 13691432320** [comment]
这是命令行后的输出log
![image](https://user-images.githubusercontent.com/41263103/77906440-90614a00-72ba-11ea-9d8d-119bd8fa333e.png)
这是application的log 
![image](https://user-images.githubusercontent.com/41263103/77906530-ae2eaf00-72ba-11ea-85ef-6e65f1fb0854.png)

**Comment by mosence** [comment]
根据你的错误来看，这是没有在flink中添加hadoop shade包

**Comment by 13691432320** [comment]
好像不是这个问题哦 shade包我是有的。 今早晨已经解决了。 
是因为，我的flink是1.10.0版本。 但是应用的jar包是1.9.1的。升级下了应用的jar包版本就好了
