### ISSUE TITLE
编译问题，无法找到com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by jollygrass** [DTStack/flinkStreamSQL#296]
编译有问题，无法找到com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT

[INFO] ------------------------------------------------------------------------
[INFO] Building sql.launcher 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] flink.sql .......................................... SUCCESS [  0.346 s]
[INFO] core ............................................... SUCCESS [  5.651 s]
[INFO] sql.kafka-base ..................................... SUCCESS [  0.004 s]
[INFO] kafka-base-sink .................................... SUCCESS [  0.586 s]
[INFO] kafka-base-source .................................. SUCCESS [  0.544 s]
[INFO] sql.kafka09 ........................................ SUCCESS [  0.004 s]
[INFO] kafka09-source ..................................... SUCCESS [  2.952 s]
[INFO] kafka09-sink ....................................... SUCCESS [  1.502 s]
[INFO] sql.kafka10 ........................................ SUCCESS [  0.004 s]
[INFO] kafka10-source ..................................... SUCCESS [  1.602 s]
[INFO] kafka10-sink ....................................... SUCCESS [  1.991 s]
[INFO] sql.kafka11 ........................................ SUCCESS [  0.004 s]
[INFO] kafka11-source ..................................... SUCCESS [  1.796 s]
[INFO] kafka11-sink ....................................... SUCCESS [  1.790 s]
[INFO] sql.kafka .......................................... SUCCESS [  0.002 s]
[INFO] kafka-source ....................................... SUCCESS [  2.141 s]
[INFO] kafka-sink ......................................... SUCCESS [  2.058 s]
[INFO] sql.rdb ............................................ SUCCESS [  0.003 s]
[INFO] rdb-sink ........................................... SUCCESS [  0.467 s]
[INFO] sql.mysql .......................................... SUCCESS [  0.002 s]
[INFO] mysql-sink ......................................... SUCCESS [  0.574 s]
[INFO] rdb-side ........................................... SUCCESS [  0.593 s]
[INFO] mysql-side ......................................... SUCCESS [  0.003 s]
[INFO] mysql-side-core .................................... SUCCESS [  0.439 s]
[INFO] mysql-async-side ................................... SUCCESS [  2.108 s]
[INFO] mysql-all-side ..................................... SUCCESS [  2.025 s]
[INFO] sql.hbase .......................................... SUCCESS [  0.002 s]
[INFO] hbase-sink ......................................... SUCCESS [  6.730 s]
[INFO] hbase-side ......................................... SUCCESS [  0.003 s]
[INFO] sql.side.hbase.core ................................ SUCCESS [  0.462 s]
[INFO] hbase-all-side ..................................... SUCCESS [  5.562 s]
[INFO] hbase-async-side ................................... SUCCESS [  6.496 s]
[INFO] sql.elasticsearch5 ................................. SUCCESS [  0.003 s]
[INFO] elasticsearch-sink ................................. SUCCESS [02:19 min]
[INFO] sql.mongo .......................................... SUCCESS [  0.004 s]
[INFO] mongo-sink ......................................... SUCCESS [  0.999 s]
[INFO] mongo-side ......................................... SUCCESS [  0.003 s]
[INFO] sql.side.mongo.core ................................ SUCCESS [  0.405 s]
[INFO] mongo-async-side ................................... SUCCESS [  2.513 s]
[INFO] mongo-all-side ..................................... SUCCESS [  1.119 s]
[INFO] sql.redis .......................................... SUCCESS [  0.002 s]
[INFO] redis-sink ......................................... SUCCESS [  0.739 s]
[INFO] redis-side ......................................... SUCCESS [  0.002 s]
[INFO] sql.side.redis.core ................................ SUCCESS [  0.508 s]
[INFO] redis-async-side ................................... SUCCESS [  2.371 s]
[INFO] redis-all-side ..................................... SUCCESS [  0.694 s]
[INFO] sql.launcher ....................................... FAILURE [  0.024 s]
[INFO] sql.sqlserver ...................................... SKIPPED
[INFO] sqlserver-side ..................................... SKIPPED
[INFO] sqlserver-side-core ................................ SKIPPED
[INFO] sqlserver-all-side ................................. SKIPPED
[INFO] sqlserver-async-side ............................... SKIPPED
[INFO] sqlserver-sink ..................................... SKIPPED
[INFO] sql.oracle ......................................... SKIPPED
[INFO] sql.side.oracle .................................... SKIPPED
[INFO] oracle-side-core ................................... SKIPPED
[INFO] oracle-all-side .................................... SKIPPED
[INFO] oracle-async-side .................................. SKIPPED
[INFO] oracle-sink ........................................ SKIPPED
[INFO] sql.cassandra ...................................... SKIPPED
[INFO] cassandra-sink ..................................... SKIPPED
[INFO] cassandra-side ..................................... SKIPPED
[INFO] sql.side.cassandra.core ............................ SKIPPED
[INFO] cassandra-async-side ............................... SKIPPED
[INFO] cassandra-all-side ................................. SKIPPED
[INFO] sql.kudu ........................................... SKIPPED
[INFO] kudu-sink .......................................... SKIPPED
[INFO] kudu-side .......................................... SKIPPED
[INFO] sql.side.kudu.core ................................. SKIPPED
[INFO] kudu-all-side ...................................... SKIPPED
[INFO] kudu-async-side .................................... SKIPPED
[INFO] sql.postgresql ..................................... SKIPPED
[INFO] postgresql-side .................................... SKIPPED
[INFO] postgresql-side-core ............................... SKIPPED
[INFO] postgresql-async-side .............................. SKIPPED
[INFO] postgresql-all-side ................................ SKIPPED
[INFO] postgresql-sink .................................... SKIPPED
[INFO] sql.serversocket ................................... SKIPPED
[INFO] serversocket-source ................................ SKIPPED
[INFO] sql.console ........................................ SKIPPED
[INFO] console-sink ....................................... SKIPPED
[INFO] sql.clickhouse ..................................... SKIPPED
[INFO] clickhouse-side .................................... SKIPPED
[INFO] clickhouse-side-core ............................... SKIPPED
[INFO] clickhouse-async-side .............................. SKIPPED
[INFO] clickhouse-all-side ................................ SKIPPED
[INFO] clickhouse-sink .................................... SKIPPED
[INFO] sql.impala ......................................... SKIPPED
[INFO] impala-sink ........................................ SKIPPED
[INFO] impala-side ........................................ SKIPPED
[INFO] impala-side-core ................................... SKIPPED
[INFO] impala-all-side .................................... SKIPPED
[INFO] impala-async-side .................................. SKIPPED
[INFO] sql.db2 ............................................ SKIPPED
[INFO] db2-sink ........................................... SKIPPED
[INFO] db2-side ........................................... SKIPPED
[INFO] db2-side-core ...................................... SKIPPED
[INFO] db2-async-side ..................................... SKIPPED
[INFO] db2-all-side ....................................... SKIPPED
[INFO] sql.polardb ........................................ SKIPPED
[INFO] polardb-sink ....................................... SKIPPED
[INFO] polardb-side ....................................... SKIPPED
[INFO] polardb-side-core .................................. SKIPPED
[INFO] polardb-all-side ................................... SKIPPED
[INFO] polardb-async-side ................................. SKIPPED
[INFO] sql.elasticsearch6 ................................. SKIPPED
[INFO] elasticsearch6-side ................................ SKIPPED
[INFO] elasticsearch6-side-core ........................... SKIPPED
[INFO] elasticsearch6-all-side ............................ SKIPPED
[INFO] elasticsearch6-async-side .......................... SKIPPED
[INFO] elasticsearch6-sink ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:18 min
[INFO] Finished at: 2020-04-01T09:21:37+08:00
[INFO] Final Memory: 145M/1375M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sql.launcher: Could not resolve dependencies for project com.dtstack.flink:sql.launcher:jar:1.0-SNAPSHOT: Could not find artifact com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by todd5167** [comment]
@jollygrass 缺少一个日志包，你加我们的钉钉群，群里有

**Comment by leeang12138** [comment]
> 编译有问题，无法找到com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building sql.launcher 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [WARNING] The POM for com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] flink.sql .......................................... SUCCESS [ 0.346 s]
> [INFO] core ............................................... SUCCESS [ 5.651 s]
> [INFO] sql.kafka-base ..................................... SUCCESS [ 0.004 s]
> [INFO] kafka-base-sink .................................... SUCCESS [ 0.586 s]
> [INFO] kafka-base-source .................................. SUCCESS [ 0.544 s]
> [INFO] sql.kafka09 ........................................ SUCCESS [ 0.004 s]
> [INFO] kafka09-source ..................................... SUCCESS [ 2.952 s]
> [INFO] kafka09-sink ....................................... SUCCESS [ 1.502 s]
> [INFO] sql.kafka10 ........................................ SUCCESS [ 0.004 s]
> [INFO] kafka10-source ..................................... SUCCESS [ 1.602 s]
> [INFO] kafka10-sink ....................................... SUCCESS [ 1.991 s]
> [INFO] sql.kafka11 ........................................ SUCCESS [ 0.004 s]
> [INFO] kafka11-source ..................................... SUCCESS [ 1.796 s]
> [INFO] kafka11-sink ....................................... SUCCESS [ 1.790 s]
> [INFO] sql.kafka .......................................... SUCCESS [ 0.002 s]
> [INFO] kafka-source ....................................... SUCCESS [ 2.141 s]
> [INFO] kafka-sink ......................................... SUCCESS [ 2.058 s]
> [INFO] sql.rdb ............................................ SUCCESS [ 0.003 s]
> [INFO] rdb-sink ........................................... SUCCESS [ 0.467 s]
> [INFO] sql.mysql .......................................... SUCCESS [ 0.002 s]
> [INFO] mysql-sink ......................................... SUCCESS [ 0.574 s]
> [INFO] rdb-side ........................................... SUCCESS [ 0.593 s]
> [INFO] mysql-side ......................................... SUCCESS [ 0.003 s]
> [INFO] mysql-side-core .................................... SUCCESS [ 0.439 s]
> [INFO] mysql-async-side ................................... SUCCESS [ 2.108 s]
> [INFO] mysql-all-side ..................................... SUCCESS [ 2.025 s]
> [INFO] sql.hbase .......................................... SUCCESS [ 0.002 s]
> [INFO] hbase-sink ......................................... SUCCESS [ 6.730 s]
> [INFO] hbase-side ......................................... SUCCESS [ 0.003 s]
> [INFO] sql.side.hbase.core ................................ SUCCESS [ 0.462 s]
> [INFO] hbase-all-side ..................................... SUCCESS [ 5.562 s]
> [INFO] hbase-async-side ................................... SUCCESS [ 6.496 s]
> [INFO] sql.elasticsearch5 ................................. SUCCESS [ 0.003 s]
> [INFO] elasticsearch-sink ................................. SUCCESS [02:19 min]
> [INFO] sql.mongo .......................................... SUCCESS [ 0.004 s]
> [INFO] mongo-sink ......................................... SUCCESS [ 0.999 s]
> [INFO] mongo-side ......................................... SUCCESS [ 0.003 s]
> [INFO] sql.side.mongo.core ................................ SUCCESS [ 0.405 s]
> [INFO] mongo-async-side ................................... SUCCESS [ 2.513 s]
> [INFO] mongo-all-side ..................................... SUCCESS [ 1.119 s]
> [INFO] sql.redis .......................................... SUCCESS [ 0.002 s]
> [INFO] redis-sink ......................................... SUCCESS [ 0.739 s]
> [INFO] redis-side ......................................... SUCCESS [ 0.002 s]
> [INFO] sql.side.redis.core ................................ SUCCESS [ 0.508 s]
> [INFO] redis-async-side ................................... SUCCESS [ 2.371 s]
> [INFO] redis-all-side ..................................... SUCCESS [ 0.694 s]
> [INFO] sql.launcher ....................................... FAILURE [ 0.024 s]
> [INFO] sql.sqlserver ...................................... SKIPPED
> [INFO] sqlserver-side ..................................... SKIPPED
> [INFO] sqlserver-side-core ................................ SKIPPED
> [INFO] sqlserver-all-side ................................. SKIPPED
> [INFO] sqlserver-async-side ............................... SKIPPED
> [INFO] sqlserver-sink ..................................... SKIPPED
> [INFO] sql.oracle ......................................... SKIPPED
> [INFO] sql.side.oracle .................................... SKIPPED
> [INFO] oracle-side-core ................................... SKIPPED
> [INFO] oracle-all-side .................................... SKIPPED
> [INFO] oracle-async-side .................................. SKIPPED
> [INFO] oracle-sink ........................................ SKIPPED
> [INFO] sql.cassandra ...................................... SKIPPED
> [INFO] cassandra-sink ..................................... SKIPPED
> [INFO] cassandra-side ..................................... SKIPPED
> [INFO] sql.side.cassandra.core ............................ SKIPPED
> [INFO] cassandra-async-side ............................... SKIPPED
> [INFO] cassandra-all-side ................................. SKIPPED
> [INFO] sql.kudu ........................................... SKIPPED
> [INFO] kudu-sink .......................................... SKIPPED
> [INFO] kudu-side .......................................... SKIPPED
> [INFO] sql.side.kudu.core ................................. SKIPPED
> [INFO] kudu-all-side ...................................... SKIPPED
> [INFO] kudu-async-side .................................... SKIPPED
> [INFO] sql.postgresql ..................................... SKIPPED
> [INFO] postgresql-side .................................... SKIPPED
> [INFO] postgresql-side-core ............................... SKIPPED
> [INFO] postgresql-async-side .............................. SKIPPED
> [INFO] postgresql-all-side ................................ SKIPPED
> [INFO] postgresql-sink .................................... SKIPPED
> [INFO] sql.serversocket ................................... SKIPPED
> [INFO] serversocket-source ................................ SKIPPED
> [INFO] sql.console ........................................ SKIPPED
> [INFO] console-sink ....................................... SKIPPED
> [INFO] sql.clickhouse ..................................... SKIPPED
> [INFO] clickhouse-side .................................... SKIPPED
> [INFO] clickhouse-side-core ............................... SKIPPED
> [INFO] clickhouse-async-side .............................. SKIPPED
> [INFO] clickhouse-all-side ................................ SKIPPED
> [INFO] clickhouse-sink .................................... SKIPPED
> [INFO] sql.impala ......................................... SKIPPED
> [INFO] impala-sink ........................................ SKIPPED
> [INFO] impala-side ........................................ SKIPPED
> [INFO] impala-side-core ................................... SKIPPED
> [INFO] impala-all-side .................................... SKIPPED
> [INFO] impala-async-side .................................. SKIPPED
> [INFO] sql.db2 ............................................ SKIPPED
> [INFO] db2-sink ........................................... SKIPPED
> [INFO] db2-side ........................................... SKIPPED
> [INFO] db2-side-core ...................................... SKIPPED
> [INFO] db2-async-side ..................................... SKIPPED
> [INFO] db2-all-side ....................................... SKIPPED
> [INFO] sql.polardb ........................................ SKIPPED
> [INFO] polardb-sink ....................................... SKIPPED
> [INFO] polardb-side ....................................... SKIPPED
> [INFO] polardb-side-core .................................. SKIPPED
> [INFO] polardb-all-side ................................... SKIPPED
> [INFO] polardb-async-side ................................. SKIPPED
> [INFO] sql.elasticsearch6 ................................. SKIPPED
> [INFO] elasticsearch6-side ................................ SKIPPED
> [INFO] elasticsearch6-side-core ........................... SKIPPED
> [INFO] elasticsearch6-all-side ............................ SKIPPED
> [INFO] elasticsearch6-async-side .......................... SKIPPED
> [INFO] elasticsearch6-sink ................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 03:18 min
> [INFO] Finished at: 2020-04-01T09:21:37+08:00
> [INFO] Final Memory: 145M/1375M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project sql.launcher: Could not resolve dependencies for project com.dtstack.flink:sql.launcher:jar:1.0-SNAPSHOT: Could not find artifact com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT -> [Help 1]

你可以移除相关依赖和关联的逻辑，我们将在最近版本中移除该maven依赖

**Comment by Yangxu1990** [comment]
编译1.10.1版本也有相同问题

[INFO] ---------------------< com.dtstack.flink:sql.core >---------------------
[INFO] Building core 1.0-SNAPSHOT                                       [2/117]
[INFO] --------------------------------[ jar ]---------------------------------
^@[WARNING] The POM for com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for flink.sql 1.0-SNAPSHOT:
[INFO]
[INFO] flink.sql .......................................... SUCCESS [  3.730 s]
[INFO] core ............................................... FAILURE [  2.846 s]
[INFO] sql.kafka-base ..................................... SKIPPED
[INFO] kafka-base-sink .................................... SKIPPED
[INFO] kafka-base-source .................................. SKIPPED
[INFO] sql.kafka09 ........................................ SKIPPED
[INFO] kafka09-source ..................................... SKIPPED
[INFO] kafka09-sink ....................................... SKIPPED
[INFO] sql.kafka10 ........................................ SKIPPED
[INFO] kafka10-source ..................................... SKIPPED
[INFO] kafka10-sink ....................................... SKIPPED
[INFO] sql.kafka11 ........................................ SKIPPED
[INFO] kafka11-source ..................................... SKIPPED
[INFO] kafka11-sink ....................................... SKIPPED
[INFO] sql.kafka .......................................... SKIPPED
[INFO] kafka-source ....................................... SKIPPED
[INFO] kafka-sink ......................................... SKIPPED
[INFO] sql.rdb ............................................ SKIPPED
[INFO] rdb-sink ........................................... SKIPPED
[INFO] sql.mysql .......................................... SKIPPED
[INFO] mysql-sink ......................................... SKIPPED
[INFO] rdb-side ........................................... SKIPPED
[INFO] mysql-side ......................................... SKIPPED
[INFO] mysql-side-core .................................... SKIPPED
[INFO] mysql-async-side ................................... SKIPPED
[INFO] mysql-all-side ..................................... SKIPPED
[INFO] sql.hbase .......................................... SKIPPED
[INFO] hbase-sink ......................................... SKIPPED
[INFO] hbase-side ......................................... SKIPPED
[INFO] sql.side.hbase.core ................................ SKIPPED
[INFO] hbase-all-side ..................................... SKIPPED
[INFO] hbase-async-side ................................... SKIPPED
[INFO] sql.elasticsearch5 ................................. SKIPPED
[INFO] elasticsearch-sink ................................. SKIPPED
[INFO] sql.elasticsearch6 ................................. SKIPPED
[INFO] elasticsearch6-side ................................ SKIPPED
[INFO] elasticsearch6-side-core ........................... SKIPPED
[INFO] elasticsearch6-all-side ............................ SKIPPED
[INFO] elasticsearch6-async-side .......................... SKIPPED
[INFO] elasticsearch6-sink ................................ SKIPPED
[INFO] sql.mongo .......................................... SKIPPED
[INFO] mongo-sink ......................................... SKIPPED
[INFO] mongo-side ......................................... SKIPPED
[INFO] sql.side.mongo.core ................................ SKIPPED
[INFO] mongo-async-side ................................... SKIPPED
[INFO] mongo-all-side ..................................... SKIPPED
[INFO] sql.redis .......................................... SKIPPED
[INFO] redis-sink ......................................... SKIPPED
[INFO] redis-side ......................................... SKIPPED
[INFO] sql.side.redis.core ................................ SKIPPED
[INFO] redis-async-side ................................... SKIPPED
[INFO] redis-all-side ..................................... SKIPPED
[INFO] sql.launcher ....................................... SKIPPED
[INFO] sql.sqlserver ...................................... SKIPPED
[INFO] sqlserver-side ..................................... SKIPPED
[INFO] sqlserver-side-core ................................ SKIPPED
[INFO] sqlserver-all-side ................................. SKIPPED
[INFO] sqlserver-async-side ............................... SKIPPED
[INFO] sqlserver-sink ..................................... SKIPPED
[INFO] sql.oracle ......................................... SKIPPED
[INFO] sql.side.oracle .................................... SKIPPED
[INFO] oracle-side-core ................................... SKIPPED
[INFO] oracle-all-side .................................... SKIPPED
[INFO] oracle-async-side .................................. SKIPPED
[INFO] oracle-sink ........................................ SKIPPED
[INFO] sql.cassandra ...................................... SKIPPED
[INFO] cassandra-sink ..................................... SKIPPED
[INFO] cassandra-side ..................................... SKIPPED
[INFO] sql.side.cassandra.core ............................ SKIPPED
[INFO] cassandra-async-side ............................... SKIPPED
[INFO] cassandra-all-side ................................. SKIPPED
[INFO] sql.kudu ........................................... SKIPPED
[INFO] kudu-sink .......................................... SKIPPED
[INFO] kudu-side .......................................... SKIPPED
[INFO] sql.side.kudu.core ................................. SKIPPED
[INFO] kudu-all-side ...................................... SKIPPED
[INFO] kudu-async-side .................................... SKIPPED
[INFO] sql.postgresql ..................................... SKIPPED
[INFO] postgresql-side .................................... SKIPPED
[INFO] postgresql-side-core ............................... SKIPPED
[INFO] postgresql-async-side .............................. SKIPPED
[INFO] postgresql-all-side ................................ SKIPPED
[INFO] postgresql-sink .................................... SKIPPED
[INFO] sql.serversocket ................................... SKIPPED
[INFO] serversocket-source ................................ SKIPPED
[INFO] sql.console ........................................ SKIPPED
[INFO] console-sink ....................................... SKIPPED
[INFO] sql.clickhouse ..................................... SKIPPED
[INFO] clickhouse-side .................................... SKIPPED
[INFO] clickhouse-side-core ............................... SKIPPED
[INFO] clickhouse-async-side .............................. SKIPPED
[INFO] clickhouse-all-side ................................ SKIPPED
[INFO] clickhouse-sink .................................... SKIPPED
[INFO] sql.impala ......................................... SKIPPED
[INFO] impala-sink ........................................ SKIPPED
[INFO] impala-side ........................................ SKIPPED
[INFO] impala-side-core ................................... SKIPPED
[INFO] impala-all-side .................................... SKIPPED
[INFO] impala-async-side .................................. SKIPPED
[INFO] sql.db2 ............................................ SKIPPED
[INFO] db2-sink ........................................... SKIPPED
[INFO] db2-side ........................................... SKIPPED
[INFO] db2-side-core ...................................... SKIPPED
[INFO] db2-async-side ..................................... SKIPPED
[INFO] db2-all-side ....................................... SKIPPED
[INFO] sql.polardb ........................................ SKIPPED
[INFO] polardb-sink ....................................... SKIPPED
[INFO] polardb-side ....................................... SKIPPED
[INFO] polardb-side-core .................................. SKIPPED
[INFO] polardb-all-side ................................... SKIPPED
[INFO] polardb-async-side ................................. SKIPPED
[INFO] sql.oceanbase ...................................... SKIPPED
[INFO] oceanbase-sink ..................................... SKIPPED
[INFO] oceanbase-side ..................................... SKIPPED
[INFO] oceanbase-side-core ................................ SKIPPED
[INFO] oceanbase-all-side ................................. SKIPPED
[INFO] oceanbase-async-side ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.019 s
[INFO] Finished at: 2020-04-28T01:51:14+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sql.core: Could not resolve dependencies for project com.dtstack.flink:sql.core:jar:1.0-SNAPSHOT: Could not find artifact com.aiweiergou:tools-logger:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by a49a** [comment]
已修复
