### ISSUE TITLE
自定义维表

### ISSUE THREAD

**Issue by lecssmi** [DTStack/flinkStreamSQL#311]
我看维表的join服务，都是使用的预设的插件。
请问有提供接口，实现自定义维表的吗？

**Comment by yangyichao-mango** [comment]
> 我看维表的join服务，都是使用的预设的插件。
> 请问有提供接口，实现自定义维表的吗？

现在插件都是实现core中的abstract class，只不过不是interface而已，如果非要interface，我觉得里面的abstract class都可以转换成interface，abstract class中实现方法都换成interface中default方法

**Comment by lecssmi** [comment]
既然可以使用自定义维表，也就意味着catalog的管理和sql的解析都需要加上新增的逻辑。请问calcite解析的部分，体验在哪里呢？我想研究研究。

**Comment by a49a** [comment]
> 既然可以使用自定义维表，也就意味着catalog的管理和sql的解析都需要加上新增的逻辑。请问calcite解析的部分，体验在哪里呢？我想研究研究。

你可以跟踪下core模块入口类。就知道如何利用Calcite解析的SQL了
