### ISSUE TITLE
打包bug

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#333]
通过mvn package/deploy出来的core.jar中带.java文件

**Comment by zjfplayer** [comment]
原因是pom.xml中的这段代码有问题
`<resources>
            <resource>
                <directory>src/main/java/</directory>
            </resource>
            <resource>
                <directory>src/main/resources/</directory>
            </resource>
        </resources>`


resource应该只包含资源文件夹

**Comment by a49a** [comment]
现已解决
