### ISSUE TITLE
DeserializationMetricWrapper类中错误

### ISSUE THREAD

**Issue by zjfplayer** [DTStack/flinkStreamSQL#335]
com.dtstack.flink.sql.format.DeserializationMetricWrapper中deserialize方法中异常处理：
 `} catch (Exception e) {
            //add metric of dirty data
            if (dirtyDataCounter.getCount() % dataPrintFrequency == 0) {
                LOG.info("dirtyData: " + new String(message));
                LOG.error("data parse error", e);
            }
            dirtyDataCounter.inc();
            return null;
        }
` 
这里应该不是dataPrintFrequency 而是dirtyPrintFrequency把？

**Comment by FlechazoW** [comment]
两个的值是一样的，只是叫法不一样

**Comment by zjfplayer** [comment]
> 两个的值是一样的，只是叫法不一样

意义不一样的 假设要改为非1000的话 那就会出问题了
