### ISSUE TITLE
PerJob提交任务时报错

### ISSUE THREAD

**Issue by lijianfeng6666526** [DTStack/flinkStreamSQL#336]
**PerJob提交任务时，报如下错误**

![image](https://user-images.githubusercontent.com/60570042/85186799-9cfbaa00-b2cd-11ea-9524-9a2e236178d1.png)

**提交命令如下：**
![image](https://user-images.githubusercontent.com/60570042/85187691-ee0e9c80-b2d3-11ea-90a0-3cbf2bf0cce1.png)

**Comment by wangyunpeng666** [comment]
confProp配置有问题，改成下面配置试下
-confProp {"time.characteristic":"EventTime"}
