### ISSUE TITLE
如何处理快速变化的维表？

### ISSUE THREAD

**Issue by hunter-xue** [DTStack/flinkStreamSQL#339]
原表在Kafka中，维表在ClickHouse中，但是维表会有频繁的新增，这样会导致原表中的有些数据join不上。这种情况如何解决。

**Comment by leeang12138** [comment]
如果是新增的数据，LRU的模式会优先从缓存中取数据，若无法命中则再查询维表数据源

**Comment by a49a** [comment]
JOIN不上，能举个例子吗
