### ISSUE TITLE
hbaseSink.md样例

### ISSUE THREAD

**Issue by caixiang027** [DTStack/flinkStreamSQL#34]
`CREATE TABLE MyResult(
    cf:channel STRING,
    cf:pv BIGINT
 )WITH(
    type ='hbase',
    zookeeperQuorum ='rdos1:2181',
    tableName ='workerinfo',
    rowKey ='cf:channel',
    parallelism ='1',
    zookeeperParent ='/hbase'
 )`
hbaseSink.md样例中cf:channel STRING，STRING类型不支持，得改成varchar才可以

**Comment by zoudaokoulife** [comment]
这个我们统一修改下。字符类型统一修改为了varchar,不支持string
