### ISSUE TITLE
[Bug]分支1.8_release  kafka source and launcher

### ISSUE THREAD

**Issue by zhuchengwen** [DTStack/flinkStreamSQL#342]
1. KafkaSourceParser 
重复了两行代码，其中setTopicIsPattern 重复，当没有给默认值时直接造成kafka source启动失败
![image](https://user-images.githubusercontent.com/56384828/87491495-df20cd00-c67a-11ea-906b-28e49103676d.png)

2.launcher目录结构， 
  1.resoureces不是resource, 会导致初始化后，拿不到log4j文件，会导致运行不打印日志
  2.test目录和main同级
![image](https://user-images.githubusercontent.com/56384828/87491510-ed6ee900-c67a-11ea-81e4-a5b0c3e81b38.png)

**Comment by a49a** [comment]
1、已经修复。
2、在下次发版时修复。
