### ISSUE TITLE
Sink-HDFS支持

### ISSUE THREAD

**Issue by easonliu30624700** [DTStack/flinkStreamSQL#348]
sink端是否考虑支持写入hdfs文件？

**Comment by a49a** [comment]
您是什么场景下有这种需求，可以再详细描述下。

**Comment by easonliu30624700** [comment]
@deadwind4 每分钟的窗口统计，结果会落地到hdfs。另外有小时级别的离线任务进行汇总，以及离线仓库hive那边也会用到数据。再者，任务运行过程中的脏数据，也要存储到hdfs。

**Comment by easonliu30624700** [comment]
@deadwind4 你们可以考虑是否有支持的必要。我这边会自己实现一个。

**Comment by a49a** [comment]
FlinkX 1.12已支持
