### ISSUE TITLE
官网数组类型字段解析示例不能运行

### ISSUE THREAD

**Issue by zhanghaoxuan-git** [DTStack/flinkStreamSQL#380]
CREATE TABLE ods (
    id INT,
    some_users ARRAY<STRING>
) WITH (
    ...
);

CREATE TABLE dwd (
    id INT,
    user_no INT,
    user_info VARCHAR
) WITH (
    type ='console',
);

INSERT INTO dwd
    SELECT id, user_info
    FROM ods_foo
    CROSS JOIN UNNEST(ods_foo.some_users) AS A (user_info);
报错不支持ARRAY<STRING>类型！！

**Comment by a49a** [comment]
现已支持，请看Kafka Source文档
