### ISSUE TITLE
flinkStreamsql 保留字和字段冲突 ，反引号无效

### ISSUE THREAD

**Issue by hqisog** [DTStack/flinkStreamSQL#384]
例如 ，flinkstreamsql 中，源表

CREATE TABLE test2(
  event_time varchar,
	id  int,
	`open` double  ,
	`close` double ,
	high double,
	low double,
	trades int,
	volume int,
	`timestamp` varchar,
	operate_type varchar,
	UDFTimeToLong(event_time, 8) as xctime,
    WATERMARK FOR xctime AS withOffset(xctime, 120000)
	)WITH(
XXXXXXXXXX
）

上面这种建源表，sql 解析失败

**Comment by hqisog** [comment]
上面 显示不对， open ,close 前后都有 反引号

open  close 是保留字

![open](https://user-images.githubusercontent.com/19682080/96563209-442c3480-12f4-11eb-8e5c-fb031f41fcd6.png)

**Comment by a49a** [comment]
我们推出了最新的1.12 在FlinkX项目里。应该没有这个问题了。你试下
