### ISSUE TITLE
不支持blink 下的 开窗函数的 RANGE 写法

### ISSUE THREAD

**Issue by yujiayue0815** [DTStack/flinkStreamSQL#395]
SELECT  
    itemID,
    itemType, 
    onSellTime, 
    price,  
    MAX(price) OVER (
        PARTITION BY itemType 
        ORDER BY onSellTime 
        RANGE BETWEEN INTERVAL '2' MINUTE preceding AND CURRENT ROW) AS maxPrice
  FROM tmall_item;

**Comment by a49a** [comment]
FlinkX 1.12 没问题，你试试
