### ISSUE TITLE
问，这个和原生的flink sql有什么区别？做了哪些原生没有的特性？

### ISSUE THREAD

**Issue by xunchangguo** [DTStack/flinkStreamSQL#397]
有这个疑问

**Comment by ithjz** [comment]
b站视频里有描述,挺清楚的

**Comment by xunchangguo** [comment]
> b站视频里有描述,挺清楚的

求地址

**Comment by FlechazoW** [comment]
b站地址：https://www.bilibili.com/video/BV1GA411J7RL?from=search&seid=17453888316576700774
