### ISSUE TITLE
我想放到 centos7上运行 , 发现没有plugin这个组件,是要自己编译吗?

### ISSUE THREAD

**Issue by ithjz** [DTStack/flinkStreamSQL#414]
我想放到 centos7上运行 , 发现没有plugin这个组件,是要自己编译吗?

F:\dtstack\project\flinkStreamSQL\plugins

没有发现这个 plugins 文件夹???

**Comment by FlechazoW** [comment]
是的，这个是需要本地编译，会生成对应的插件包。后续操作可以看下我们的文档内容，也可以加入我们的钉钉群一起讨论
