### ISSUE TITLE
[Flink-CEP-SQL] 经过pattern match 出来的stream 可以和维表join吗

### ISSUE THREAD

**Issue by hongtao12310** [DTStack/flinkStreamSQL#42]
很高兴看到有人commit cep sql相关代码

需求：
1. kafka作为source
2. 经过cep
3. join mysql 维表
4. sink到mysql/其他

这种目前可以用一条sql表达吗？

**Comment by yangsishu** [comment]
可以的，但是我们还没经过测试，只是把代码合并进来，后续会进行测试
