### ISSUE TITLE
yarn模式提交任务时，内部是否是使用的交互模式提交任务？

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#44]
使用on yarn 模式提交任务，调试了源代码。
请问这里是使用的interactive交互模式吗？
![image](https://user-images.githubusercontent.com/25834421/48554405-47089880-e919-11e8-8826-f88ac42cb38c.png)

**Comment by yangsishu** [comment]
flink on yarn 模式下提交任务有两种：
1.事先启动一个yarn session，任务往这个yarn session 提交，就是多个任务共用一个yarn session，优点是资源利用率比较高，缺点是多个任务有可能会相互影响
2.per-job 模式，一个任务就会启动一个yarn session，优缺点跟上面的正好相反

**Comment by nuaabuaa07** [comment]
flinkstreamsql需要的是采用，”事先启动一个yarn session”这种形式？
