### ISSUE TITLE
1.6版本的支持Flink1.6的on yarn模式吗？

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#54]

**Comment by yangsishu** [comment]
是支持的，只不过现在1.6的代码不是最新的，我们最近会把最新的代码合并到1.6上，在根据1.6做下兼容测试

**Comment by nuaabuaa07** [comment]
请问，是支持Flink1.6的on yarn 还是standalone模式呢？之前的版本，好像不同部署模式的支持情况不太一样。
