### ISSUE TITLE
Kafkasource 是否支持通配符、正则表达式的topic？

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#57]
kafkasource源时，topic是否支持通配符或者正则表达式形式

下一版本支持。

**Comment by yangsishu** [comment]
现在不支持

**Comment by R-CodeBoy** [comment]
kafka source是否支持1.1版本的

**Comment by R-CodeBoy** [comment]
你好  我测了sql 的join 好像不支持这种a.x =b.x or a.z = b.z 逻辑条件，请问后续支持吗

**Comment by yangsishu** [comment]
这个后面会加上

**Comment by todd5167** [comment]
> kafkasource源时，topic是否支持通配符或者正则表达式形式
> 
> 下一版本支持。

**Comment by todd5167** [comment]
@nuaabuaa07   现在支持topic正则匹配（test.*）、多个topic(topic1,topic2)
