### ISSUE TITLE
redis输出源，测试，没有任何数据输出。

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#62]
![image](https://user-images.githubusercontent.com/25834421/49728999-31d02100-fcaf-11e8-91c8-77fda9a5bb0d.png)

**Comment by nuaabuaa07** [comment]
![image](https://user-images.githubusercontent.com/25834421/49730813-7e6a2b00-fcb4-11e8-98d6-f6026ec5df99.png)

**Comment by yanxi0227** [comment]
database就是redis里需要select的数据库，tablename是一个字段，用于拼接key，使key值唯一，方便映射到关系型数据库

**Comment by nuaabuaa07** [comment]
你好，我依旧无法在redis中得到输出结果。
sql如下：

 CREATE TABLE StreamSrcTableee(
    name VARCHAR,
    height bigint
 )WITH(
    type ='kafka10',
    bootstrapServers ='xxx.xxx.xxx.xxx:9092',
    zookeeperQuorum ='xxx.xxx.xxx.xxx:2181/kafka',
    offsetReset ='latest',
    topic ='test_flink2',
    parallelism ='3'
 );




CREATE TABLE myresult(
    name varchar,
    PRIMARY KEY(name)
 )WITH(
    type='redis',
    url='xxx.xxx.xxx.xxx:6379',
    database='0',
    tableName='myresult'
 );
 
 
 
insert
 into
	myresult
	select 
		a.name
	from
		StreamSrcTableee as a;

从kafka读出数据输出到mysql没问题。
redis的配置文件中密码已经取消了，redis的bind ip也注释掉了，安全模式也注释掉了，从其他地方访问读写没问题。
请问，还需要在redis中配置什么吗？上面的sql中有什么问题吗？

**Comment by nuaabuaa07** [comment]
我的redis版本是
 Redis 5.0.2 (00000000/0) 64 bit

**Comment by YuangZhang** [comment]
请问你解决了吗，我也遇到这个问题，这里的database应该填什么呀，tableName是随便填字段吗
