### ISSUE TITLE
kafka source是否支持groupid设置？设置offset为earlist不起作用，还是从latest读增量数据

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#63]

**Comment by ayinghaha** [comment]
> kafka source是否支持groupid设置？设置offset为earlist不起作用，还是从latest读增量数据

我看了源码里这两个属性是没有进行设置的，需要修改下

**Comment by todd5167** [comment]
offset已经修改，下次发布合并

**Comment by todd5167** [comment]
> kafka source是否支持groupid设置？设置offset为earlist不起作用，还是从latest读增量数据

支持groupId参数设置。下一版修复Offset总是为latest的Bug.

**Comment by nuaabuaa07** [comment]
![image](https://user-images.githubusercontent.com/25834421/49741004-6b655400-fcd0-11e8-8c08-917c4e23340c.png)
测试使用groupid也没啥用啊。

**Comment by nuaabuaa07** [comment]
@todd5167 如何使用groupid呢？我设置了groupId，但是不起作用。麻烦看一下上面的例子里配置的正确吗？

**Comment by R-CodeBoy** [comment]
请问是否支持历史维表的join

**Comment by R-CodeBoy** [comment]
你们现在最新的代码是1.6_dev分支吗，谢谢

**Comment by R-CodeBoy** [comment]
你好,在问一个问题，在测试的过程中，发现流与维表的join的条件需要包含维表的主键，但是这个Join 的条件不是shuffle 的key,不一定就是维表的主键吧  还有看到的维表的cache的key好像就是primary key，这样维表数据增加的时候还好，但是修改维表的数据就不太好了，谢谢

**Comment by todd5167** [comment]
@R-CodeBoy   维表的 PRIMARY KEY 字段就是join关联的字段和真实数据库主键没有关系。
维表缓存是定时刷新的，有缓存超期时间的。

**Comment by todd5167** [comment]
@nuaabuaa07   现在支持groupId,offset参数可以设置earlist
