### ISSUE TITLE
提交任务至yarn session时，如果yarn上有多个yarn session实例，可否指定具体的yarn session id？

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#66]
![image](https://user-images.githubusercontent.com/25834421/49806734-6e754880-fd93-11e8-9d5d-7e24ce78d017.png)
启动了多个yarn session。
是否可以提交作业时，指定到对应的yarn session上？

**Comment by yangsishu** [comment]
现在是根据name来的

**Comment by nuaabuaa07** [comment]
你说的name是指“Flink session cluster”这里吗？提交任务时，在哪里设置name呢

**Comment by yangsishu** [comment]
这个现在没做成配置，代码写死的
