### ISSUE TITLE
1.6版本本地模式指定-localSqlPluginPath找不到具体执行jar的问题

### ISSUE THREAD

**Issue by mjbrandy** [DTStack/flinkStreamSQL#69]
新人刚接触这套开源系统，请问下，我在本地执行时，参数-localSqlPluginPath传入了打包后的本地的插件目录  E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins

![image](https://user-images.githubusercontent.com/45843159/49924056-38011000-fef0-11e8-9d1f-49c3a6718024.png)

我源头表用的是kafka010
当执行到PluginUtil.java的getJarFileDirPath方法时，拿到的File jarFile仅仅是一个目录：E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins\kafka010source
并没有指向这里面具体的jar文件，所以报错了。
java.lang.RuntimeException: path E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins\kafka010source not exists!!!
请问是我入参配置有问题么

**Comment by mjbrandy** [comment]
我的本地入参是这些：-sql d:\test.sql -name testflinksql -localSqlPluginPath E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins -confProp {\"time.characteristic\":\"EventTime\",\"sql.checkpoint.interval\":10000}

**Comment by mjbrandy** [comment]
Plugin目录和下面对应的jar包文件我也检查过了，都存在
![image](https://user-images.githubusercontent.com/45843159/49925677-97611f00-fef4-11e8-95a3-a79b8d796613.png)

**Comment by yanxi0227** [comment]
路径是kafka10source，前缀是由源表type传入

**Comment by mjbrandy** [comment]
> 路径是kafka10source，前缀是由源表type传入

官方给的例子，定义的-localSqlPluginPath参数，就到plugin这一级，如果这里指定E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins\kafka10source肯定有问题了

会报这个错，路径拼接出来，肯定不对
Exception in thread "main" java.lang.RuntimeException: path E:\ideaworkspace\flinkStreamSQL-1.6.0\plugins\kafka10source\kafka010source not exists!!!

**Comment by yanxi0227** [comment]
![image](https://user-images.githubusercontent.com/15013176/49926301-3a666880-fef6-11e8-89d8-c307e069b90d.png)
传入的路径没有问题，源表type设置为kafka10

**Comment by mjbrandy** [comment]
您好，我知道您的意思，我的sql就是按您说的那样写的，我自己跟的断点调试的

![image](https://user-images.githubusercontent.com/45843159/49926964-d2188680-fef7-11e8-84a0-4d9a2cb88f25.png)

您看，我断点到这句的时候，jarPath它就仅仅指向kafka10source这个目录，我要的是下面那个
kafka10-source.jar包，如果您方便，您可以打印一下您的程序，执行到PluginUtil的getJarFileDirPath这个方法的时候，jarPath的值么
