### ISSUE TITLE
can not compile with flink 1.6

### ISSUE THREAD

**Issue by xianhuawei** [DTStack/flinkStreamSQL#7]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sql.core: Compilation failure
[ERROR] /Users/xianhua.wei/Downloads/flinkStreamSQL/core/src/main/java/com/dtstack/flink/sql/MyLocalStreamEnvironment.java:[103,22] no suitable method found for setLong(org.apache.flink.configuration.ConfigOption<java.lang.String>,long)
[ERROR]     method org.apache.flink.configuration.Configuration.setLong(java.lang.String,long) is not applicable
[ERROR]       (argument mismatch; org.apache.flink.configuration.ConfigOption<java.lang.String> cannot be converted to java.lang.String)
[ERROR]     method org.apache.flink.configuration.Configuration.setLong(org.apache.flink.configuration.ConfigOption<java.lang.Long>,long) is not applicable
[ERROR]       (argument mismatch; org.apache.flink.configuration.ConfigOption<java.lang.String> cannot be converted to org.apache.flink.configuration.ConfigOption<java.lang.Long>)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sql.core

**Comment by yangsishu** [comment]
suport flink 1.4 and 1.5 now
