### ISSUE TITLE
关于redis的DDL语法与实际存储在redis中的数据结构的映射关系

### ISSUE THREAD

**Issue by mjbrandy** [DTStack/flinkStreamSQL#76]
如题。各位开发这个应用的大神，能否给一个详细一些的redis维表的例子，尤其是redis端存储的实际数据的结构。比如我
create table redisSideTable(
	PRIMARY KEY(user_id),
	user_name varchar,
        user_id varchar,
	user_sex varchar,	
    PERIOD FOR SYSTEM_TIME
 )WITH(
    type='redis',    
    url='xxxxxxxxxx:xxxx',
    password='',
    database='0',
    tableName='sidetest',
    cache = 'LRU',
    cacheTTLMs='10000'
 );

这样的用户表，假如有5000个用户信息，用什么redis数据结构来存储这5000条数据信息呢

**Comment by yangsishu** [comment]
https://github.com/DTStack/flinkStreamSQL/blob/master/docs/redisSide.md

**Comment by RockeyCui** [comment]
> 
> 
> 如题。各位开发这个应用的大神，能否给一个详细一些的redis维表的例子，尤其是redis端存储的实际数据的结构。比如我
> create table redisSideTable(
> PRIMARY KEY(user_id),
> user_name varchar,
> user_id varchar,
> user_sex varchar,
> PERIOD FOR SYSTEM_TIME
> )WITH(
> type='redis',
> url='xxxxxxxxxx:xxxx',
> password='',
> database='0',
> tableName='sidetest',
> cache = 'LRU',
> cacheTTLMs='10000'
> );
> 
> 这样的用户表，假如有5000个用户信息，用什么redis数据结构来存储这5000条数据信息呢

你好，请问你解决这个问题了吗？
