### ISSUE TITLE
任务失败以后，指定savepoint后任务并没有从故障点恢复

### ISSUE THREAD

**Issue by hengyuan** [DTStack/flinkStreamSQL#77]

**Comment by hengyuan** [comment]
sh submit.sh -sql ./sql.txt -name test_streaming -localSqlPluginPath /home/jeff/IdeaProjects/flinkStreamSQL/plugins -confProp \{\"sql.checkpoint.interval\":\"10000\",\"sql.checkpoint.cleanup.mode\":\"false\",\"flinkCheckpointDataURI\":\"file:///home/jeff/flink\"\} -savePointPath /home/jeff/flink/1186bb383763dae5fbb1bfb27c9dfc91/chk-18/_metadata -allowNonRestoredState true 大神指教一下，我按照这些参数设置以后，kill掉任务以后，再起来状态并没有继续

**Comment by yangsishu** [comment]
你这是本地模式是不支持的，只有是yarn或standalone模式才有用
