### ISSUE TITLE
创建mysql维表的时候报错

### ISSUE THREAD

**Issue by hackyun** [DTStack/flinkStreamSQL#84]
Exception in thread "main" java.lang.ClassNotFoundException: com.dtstack.flink.sql.source.mysql.table.MysqlSourceParser  这个包是没有上传么？我在源码里面没有看到。

**Comment by yangsishu** [comment]
你用的是那个版本

**Comment by hackyun** [comment]
我用的主线里面的

**Comment by yangsishu** [comment]
你的sql贴下，MysqlSourceParser 这个类是没有的，源表是没有mysql的

**Comment by yangsishu** [comment]
你是不是把源表用mysql了

**Comment by hackyun** [comment]
CREATE TABLE test2(
    user_id varchar,
    user_name varchar
 )WITH(
    type ='mysql',
    url ='jdbc:mysql://192.168.56.1:3306/cs_qy?charset=utf8',
    userName ='root',
    password ='root',
    tableName ='test2',
    parallelism ='1'
 );

CREATE TABLE test(
    user_id varchar,
    user_name varchar,
    user_code varchar
 )WITH(
    type ='mysql',
    url ='jdbc:mysql://192.168.56.1:3306/cs_qy?charset=utf8',
    userName ='root',
    password ='root',
    tableName ='test',
    parallelism ='1'
 );

insert into test2 select user_id,user_name from test;   
这是我的SQL  我想测试一下先。

**Comment by hackyun** [comment]
是的 我的源表是mysql，现在还不支持mysql源表是么？

**Comment by yangsishu** [comment]
你看下github介绍，源表我们支持kafka的

**Comment by yangsishu** [comment]
mysql支持维表和结果表，你上面的那种写法，我们认为是把mysql当成源表用，而不是维表

**Comment by hackyun** [comment]
好的，我看了 维表和源表的建表语句没啥差别 我就试了一下，我在按照文档里面给的例子试试看。
