### ISSUE TITLE
配置项savePointPath 和 flinkCheckpointDataURI区别

### ISSUE THREAD

**Issue by nuaabuaa07** [DTStack/flinkStreamSQL#87]
这2个是只要设置一个就可以了？还是都需要设置呢？区别是什么呢？

**Comment by yangsishu** [comment]
savepoint 和checkpoint 是有所不同的

**Comment by yangsishu** [comment]
具体的可以到网上搜下

**Comment by lixiyuan123** [comment]
其实关于咱们这儿提供的savePointPath 和 flinkCheckpointDataURI功能，我想请教个问题。
咱们这儿提供的这两个参数只是让我们保存了chenkpoint数据。
那么如果我想让我的SQL脚本 启动的时候还是想从上一次的检查点恢复 启动，我yarnPer提交任务的时候如何指定？？？  感谢！
