### ISSUE TITLE
SQL对CEP的支持什么时候开源呢

### ISSUE THREAD

**Issue by xuxiaoxiao89** [DTStack/flinkStreamSQL#90]
从flink1.7开始，flink已部分支持了SQL CEP，我们需要在本项目中做哪些修改吗，我在core模块下修改了InsertSqlParser.java这个类，增加了对关键字MATCH_RECOGNIZE的识别，代码如下：
case SELECT:
			SqlNode sqlFrom = ((SqlSelect) sqlNode).getFrom();
			if (sqlFrom.getKind() == IDENTIFIER) {
				sqlParseResult.addSourceTable(sqlFrom.toString());
			} else {
				parseNode(sqlFrom, sqlParseResult);
			}
			break;
		case MATCH_RECOGNIZE:
			SqlNode sqlMr = ((SqlMatchRecognize)sqlNode).getTableRef();
			if (sqlMr.getKind() == IDENTIFIER) {
				sqlParseResult.addSourceTable(sqlMr.toString());
			} else {
				parseNode(sqlMr, sqlParseResult);
			}
			break;
		case JOIN:
……………………
现在是可以运行，但没有预想的结果输出，我单独写kafka消费和SQL CEP是可以的，用的同样的测试数据，不知道还有哪个地方需要修改，请多多指教~

**Comment by xuxiaoxiao89** [comment]
问题已经解决了，现在可以本地，华为平台yarn模式跑SQL 了包括 CEP SQL

**Comment by jonsnow233** [comment]
> 问题已经解决了，现在可以本地，华为平台yarn模式跑SQL 了包括 CEP SQL

请问怎么解决的

**Comment by xuxiaoxiao89** [comment]
如果你用华为的FI，需要替换华为对Flink的增强包，不能用开源的，还有就是你的CEP SQL是否正确（要符合华为的CEP SQL语法），还有就是样例数据，具体的可以加我QQ

**Comment by jonsnow233** [comment]
好的，我qq是1193216154，麻烦加一下我，我看不到你qq




------------------ 原始邮件 ------------------
发件人: "xuxiaoxiao89"<notifications@github.com>;
发送时间: 2019年8月22日(星期四) 下午3:33
收件人: "DTStack/flinkStreamSQL"<flinkStreamSQL@noreply.github.com>;
抄送: "陈勇"<me1193216154@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [DTStack/flinkStreamSQL] SQL对CEP的支持什么时候开源呢 (#90)




如果你用华为的FI，需要替换华为对Flink的增强包，不能用开源的，还有就是你的CEP SQL是否正确（要符合华为的CEP SQL语法），还有就是样例数据，具体的可以加我QQ

**Comment by yangsishu** [comment]
已经支持了cep
