### ISSUE TITLE
1.6分支是否支持kafka sink,如果支持，能否给个参数设置？

### ISSUE THREAD

**Issue by gcstar** [DTStack/flinkStreamSQL#99]

**Comment by todd5167** [comment]
CREATE TABLE MyResult(
    CHANNEL varchar,
    pv INT,
	xdate timestamp,
	xtime date
 )WITH(
    --type='kafka09',
	--kafka.topic ='mqTest04',
	--kafka.bootstrap.servers  ='xxx:9092',
    --kafka.zookeeper.quorum ='xxx:2181/kafka',
	--sinkdatatype ='json'
	
	--fielddelimiter ='\|'
	
	---08 user
	---kafka.zookeeper.connect='xx:2181/kafka'
	
	--type='mysql',
    --url='jdbc:mysql://xxx:3306/test?charset=utf8',
    --userName='dtstack',
    --password='xx',
	
	type='console'
	
	--type='sqlserver',
    --url='jdbc:jtds:sqlserver://xx:1433;DatabaseName=aa',
    --userName='sa',
    --password='xxxx',
	
	--type='oracle',
	--url='jdbc:oracle:thin:@xxx:1521:xe',
	--userName='dtstack',
    --password='xxx',
    --tableName='pv1'
	
 );
@gcstar

**Comment by gcstar** [comment]
@todd5167 Thanks!
